### DISCUSSION TITLE
Got OIDC working with Authentik

### DISCUSSION THREAD

**Discussion by FunDeckHermit** [drakkan/sftpgo#1037] [Ideas]
Hi,

After reading both [Authentik](https://goauthentik.io/docs/)'s and sftpgo docs I was sure they would be compatible somehow. 
In Authentik, just make an OIDC provider and assign it to any empty application. 
<img src="https://user-images.githubusercontent.com/5075692/198385468-faf12157-ba8b-42b6-97b5-53838ba9fe33.png" width="400">

Here is my Docker compose config with hardcoded environment variables. The scopes are left empty, I did not need them. 
docker-compose.yml file:
```
version: '3.6'

services:
  sftpgo:
    image: drakkan/sftpgo:edge
    container_name: sftpgo
    user: 1000:1000
    restart: on-failure
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL=https://auth.example.com/application/o/sftpgologin/
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID=ab15afd912803945e9186adea5d6758d77df2f86
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD=preferred_username
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD=sftpgo_role
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL=http://storage.example.com/
      - SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET=471f2f3edb0c298632a551d083f377399e88a5b965d56b991d1a0641944de409514e09e38c00e09c177ed6a0e1d2b87dadfc46c8b1d6f7be11459e2b70c416e9
    volumes:
      - ./data:/srv/sftpgo/data
      - ./config:/var/lib/sftpgo
      - /mnt:/srv/server-webdav
    ports:
      - 8080:8080
      - 2022:2022
```
After this, create a user in sftpgo that is known in Authentik. Then just click the button and login. It was surprisingly painless to get going.
