### DISCUSSION TITLE
Make Virtual folder auto shared/avaialable for all old and new users

### DISCUSSION THREAD

**Discussion by t-abraham** [drakkan/sftpgo#1291] [General]
Hi. I have this following docker file to run the sftpgo:edge-alpine-slim. I was wondering if there is any way to keep the /shared folder and its contents as a default folder for all the new and old users without manually adding them?

```
version: "3.5"
services:  
  sftpgo:
    image: ${IMAGE_URL}:${IMAGE_TYPE}
    container_name: ${SERVICE_NAME}
    restart: always
    logging:
      options:
        max-size: 50m
    env_file:
      - .env
    volumes:
      - "/home/data/${SERVICE_NAME}/srv/sftpgo:/srv/sftpgo"
      - "/home/data/${SERVICE_NAME}/var/lib/sftpgo:/var/lib/sftpgo"
      - "/home/data/shared:/shared"
    networks:
      - administration
      - edgerouter
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edgerouter"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=${SERVICE_TYPE}"
      - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_PORT}"
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE_MODE}"
    ports:
      - "2022:2022"
networks:
  administration:
    name: administration
    driver: bridge
  edgerouter:
    name: edgerouter
    driver: bridge
```
