### DISCUSSION TITLE
Running in Docker with S3 backend causes a slowdown

### DISCUSSION THREAD

**Discussion by crcollver** [drakkan/sftpgo#1502] [Q&A]
Hi all!

I can't figure out what might be causing this, so I'm hoping it's a silly Docker configuration thing on my end.  I've been using the SFTPGo binary as a systemd service, but have slowly been moving everything to Docker.  I'm using docker compose, and have followed the docs for the Docker container.  It seems like my Docker configuration is fetching everything much slower from S3.

There [is a similar discussion](https://github.com/drakkan/sftpgo/discussions/886), but I didn't want to revive an old thread and I wanted to include more information.

I am running on Debian 11 using SFTPGo 2.5.6.  I have not tried other versions of SFTPGo as I just recently upgraded to start this Docker project.

To be clear, navigating to SFTPGo pages such as Users, Folders, Events, etc. within this current configuration works great, it's only the data that is being fetched from S3 that is slow.

Here is my compose:
```yaml
version: "3.8"
services:
  sftpgo:
    image: drakkan/sftpgo:v2.5.6
    container_name: sftpgo
    user: 997:996
    networks:
      - sftpgo
    volumes:
      - /srv/docker/sftpgo/data:/srv/sftpgo
      - /srv/docker/sftpgo/config:/var/lib/sftpgo
      - /srv/docker/sftpgo/config/custom:/usr/share/sftpgo/static/custom
    env_file:
      - sftpgo.env
    ports:
      - 2222:2022
      - 80:8080
    restart: unless-stopped
networks:
  sftpgo:
    name: sftpgo
```
My `sftpgo.env` file is as follows:

```
SFTPGO_COMMON__SETSTAT_MODE=1

# Custom branding for WebUI, both client and admin side can be adjusted.
SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__FAVICON_PATH="/custom/favicon.ico"
SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__LOGO_PATH="/custom/icon.png"
SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__LOGIN_IMAGE_PATH="/custom/icon.png"

SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__FAVICON_PATH="/custom/favicon.ico"
SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__LOGO_PATH="/custom/icon.png"
SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__LOGIN_IMAGE_PATH="/custom/icon.png"

# Hides link to admin site if on Client.
SFTPGO_HTTPD__BINDINGS__0__HIDE_LOGIN_URL="2"

# Removes max upload size restriction for Web Client.
SFTPGO_HTTPD__MAX_UPLOAD_FILE_SIZE=0
```

The Docker logs are showing that I'm waiting about 3.5s until the objects from the S3 bucket populate in SFTPGo.
```
{"level":"debug","time":"2023-12-30T02:04:09.433","sender":"httpd","local_addr":"172.23.0.2:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.1.13:63801","request_id":"397e69e45657/h5zyeG0EqZ-000005","uri":"http://mydomain.com/web/client/dirs?path=%2F&_=1703901846002","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0","resp_status":200,"resp_size":207,"elapsed_ms":3578}
```

Whereas the binary running as a systemd service (using the same environment variables) loads immediately:
```
{"level":"debug","time":"2023-12-30T02:21:13.343","sender":"httpd","local_addr":"192.168.1.69:8080","method":"GET","proto":"HTTP/1.1","remote_addr":"192.168.1.13:64627","request_id":"6c02437fc84f/WJr9Y0w1bn-000045","uri":"http://mydomain.com/web/client/dirs?path=%2F&_=1703902873457","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0","resp_status":200,"resp_size":207,"elapsed_ms":49}
```

Let me know what I might be doing wrong, thanks!
