### DISCUSSION TITLE
branding logo issue with docker

### DISCUSSION THREAD

**Discussion by abdeldjalil-fellah** [drakkan/sftpgo#1620] [General]
with the file below the logo is set successfully but all other static files cannot be accessed:
`/static/assets/css/style.bundle.css`
`/static/assets/plugins/global/plugins.bundle.css`
...

the logo is located in the host in both `./config/static/logo.png` and `./branding/logo.png`
the issue also occurs when uncomment `./branding/logo.png` volume

```
version: "3.8"
services:
  main:
    image: drakkan/sftpgo:latest
    restart: always
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__LOGO_PATH=logo.png
    ports:
      - "8080:8080"
      - "2022:2022"
    volumes:
      - ./config:/var/lib/sftpgo
      - ./storage:/srv/sftpgo
#      - ./branding/logo.png:/var/lib/sftpgo/static/logo.png
```

**Comment by abdeldjalil-fellah** [comment]
this works by using `/usr/share/sftpgo/static` without `SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__LOGO_PATH`
but it set the icon for both the admin and the client

```
version: "3.8"
services:
  main:
    image: drakkan/sftpgo:latest
    restart: always
    ports:
      - "8080:8080"
      - "2022:2022"
    volumes:
      - ./config:/var/lib/sftpgo
      - ./storage:/srv/sftpgo
      - ./branding/logo.png:/usr/share/sftpgo/static/img/logo.png
      - ./branding/logo.png:/usr/share/sftpgo/static/img/login_image.png
```
