### DISCUSSION TITLE
Token persistence issue / token issue with several pods

### DISCUSSION THREAD

**Discussion by genseb13011** [drakkan/sftpgo#1792] [Q&A]
Hi,

I've deployed SFTPGo using the **https://charts.sagikazarmark.dev/sftpgo** helm chart version **0.19.0.**

I'm trying to configure High availability so I've set the `replicaCount: 2`

I've notice random issue with token generated.

```
{
    "error": "token is unauthorized",
    "message": "Unauthorized"
}
```

I've set the `is_shared: 1` (and also `token_validation: 1` in doubt) but still have same issue.

I've also notice that when I kill my pods, token are not persisted.

What I want is that my generated tokens are well usable on any SFTPGo pods/instance and that the token persists even when pods restarts.

Below my config declaration

```
        config:
          data_provider:
            is_shared: 1
            password_hashing:
              algo: argon2id
            sslmode: 1
          common:
            defender:
              enabled: true
              driver: provider
              ban_time: 30
              ban_time_increment: 50
              threshold: 15
              score_invalid: 2
              score_valid: 1
              score_limit_exceeded: 0
              score_no_auth: 0
              observation_time: 30
              entries_soft_limit: 100
              entries_hard_limit: 150
          httpd:
            token_validation: 1
```

Thanks for your help.

Seb.
