### DISCUSSION TITLE
Webdav server not enabled in a docker install

### DISCUSSION THREAD

**Discussion by emailforos** [drakkan/sftpgo#1945] [Q&A]
Hi.
I'm trying to self-host a webdav server and I tried to deply it with Sftpgo image.

My compose.yml file is:

```
services:
    sftpgo:
        image: ghcr.io/drakkan/sftpgo:latest
        container_name: sftpgo
        ports:
            - '58080:8080'
            #        - '2022:2022'
            #        - '2121:2121'
            - '10080:10080'
        volumes:
            - type: bind
              source: /home/user/docker/sftpgo/sftpgodata
              target: /srv/sftpgo
            - type: bind
              source: /home/user/docker/sftpgo/sftpgohome
              target: /var/lib/sftpgo
        environment:

            - SFTPGO_HTTPD_BINDINGS_0_PORT=58080
            - SFTPGO_HTTPD_BINDINGS_0_ADDRESS=0.0.0.0
            - SFTPGO_WEBDAVD_BINDINGS_0_PORT=10080
        restart: unless-stopped
        networks:
            dockernet:
                ipv4_address: ${APP_SFTPGO_IP}
networks:
  dockernet:
    external: true
```

And when I access to the webui, I see in - Server Manager => Status that the webdav server is disabled.

![image](https://github.com/user-attachments/assets/1fb9451e-6dc8-4ac5-a982-0aeecc657e8c)

Have anybody an idea or suggestion of whats going wrong?

I use Nginx Proxy Manager as a reverse proxy.

Thank you in advance for your help (and sorry for my faulty english - it's not my mother tonge).
