### DISCUSSION TITLE
Docker Compose

### DISCUSSION THREAD

**Discussion by Saxintosh** [drakkan/sftpgo#678] [Q&A] [answered]
Hello,
I am trying to use Docker Compose with this configuration:

```
version: '3.6'

services:
  sftpgo:
    image: drakkan/sftpgo:alpine-slim
    container_name: sftpgo
    volumes:
      - /root/docker/sftpgo/data:/srv/sftpgo/data
      - /root/docker/sftpgo/config:/var/lib/sftpgo
    ports:
      - 8080:8080
      - 2022:2022
```

I created the paths:
`/root/docker/sftpgo/data` e `/root/docker/sftpgo/config`

When I create a user from web UI, the relevant folders are not created in `/srv/sftpgo/data`.

Any ideas?

Thanks

**Comment by drakkan** [comment, marked as answer]
Hi,

SFTPGo runs using 1000 as UID/GID. It is unlikely that a non root user can write to `/root/docker/sftpgo`. Please create the mapped paths outside the root user home dir and ensure that the system user with id 1000 can write there

**Reply by Saxintosh** [reply]
Thank you. I had already tried but without success... I was misled by the fact that the "data" and "config" folders have to be created in advance!

Thanks again.

**Comment by teckwrek** [comment]
Unfortunately, the instructions don't work for Mac OSX. Was using that for learning and development. I was trying to override the sftpgo.json file for customization. Putting down solution here for anyone who comes looking...

The basic problem is that osx will not transfer the set UID/GID on the host filesystem into the container on mount. https://stackoverflow.com/a/61009413

To make it work, had to create named volumes. That would allow docker in OSX to manipulate the host bind appropriately.

```
services:
  sftpgo:
    image: 'drakkan/sftpgo:alpine'
    restart: always
    user: '1000' # Not sure if needed.
    ports:
      - 8080:8080 #admin
      - 2022:2022 #sftp
    volumes:
      - sftpgo-data:/srv/sftpgo
      - sftpgo-home:/var/lib/sftpgo
      - ./sftpgo/sftpgo.json:/var/lib/sftpgo/sftpgo.json
volumes:
  sftpgo-data:
  sftpgo-home:
```
