### DISCUSSION TITLE
SFTPGo 2.2.2 - FTP MGET

### DISCUSSION THREAD

**Discussion by tweingart89** [drakkan/sftpgo#770] [Q&A] [answered]
Hello,

we have a customer who wants to fetch files from a directory via FTP from our SFTPGo 2.2.2.
He uses the MGET (MGET *.xml) command. Unfortunately nothing happens, no files are transferred.
With SFTP it works, the customer just unfortunately can't use SFTP..
Why does it not work with FTP?

We are using sFTPGo in Docker. 

docker-compose.yml:
```
version: "3.4"
services:
  sftpgo:
    image: drakkan/sftpgo:v2.2.1
    container_name: ils-sftpgo
    network_mode: host
    restart: always
    ports:
      - 8080:8080
      - 2022:2022 #sftp
      - 2121:2121 #ftp 
      - 50000-50100:50000-50100 #passive mode port range        
    environment:
      - SFTPGO_FTPD__BINDINGS__0__PORT=2121
      - TZ=Europe/Berlin
    volumes: 
      - /data/ils-sftp-go/data:/srv/sftpgo
      - /data/ils-sftp-go/home:/var/lib/sftpgo
```

Thanks for the help!
