### DISCUSSION TITLE
ACME and docker

### DISCUSSION THREAD

**Discussion by szelga** [drakkan/sftpgo#873] [Q&A] [answered]
hello.
can't seem to find how to configure ACME for docker. my env variables are:

```yaml
      SFTPGO_ACME__DOMAINS__0: "ftp.company.name"
      SFTPGO_ACME__EMAIL: "admin@company.name"
      SFTPGO_ACME__KEY_TYPE: "4096"
      SFTPGO_ACME__CERTS_PATH: "/var/lib/sftpgo/certs"
      SFTPGO_ACME__CA_ENDPOINT: "https://acme-v02.api.letsencrypt.org/directory"
      SFTPGO_ACME__RENEW_DAYS: 30
      SFTPGO_ACME__HTTP01_CHALLENGE__0__PORT: 8085
      SFTPGO_ACME__HTTP01_CHALLENGE__0__PROXY_HEADER: ""
      SFTPGO_ACME__HTTP01_CHALLENGE__0__WEBROOT: "/var/www/ftp.company.name"
      SFTPGO_ACME__TLS_ALPN01_CHALLENGE__0__PORT: 0
```

but the error goes like this:

```
sftpgo    | {"level":"info","time":"2022-06-10T12:53:32.721","sender":"acme","message":"no domains configured, acme disabled"}
```

is it a bug, or do I not understand how to spell env variables correctly?
