### ISSUE TITLE
Using goreleaser for binary releases

### ISSUE THREAD

**Issue by sandreas** [drakkan/sftpgo#1]
Hey there,

great project. What do you think about using `goreleaser` (https://goreleaser.com/) for binary releases? 
I used it in some projects and it was a great tool for binary releases.

See https://github.com/sandreas/graft/blob/master/.goreleaser.yml for an example.

sandreas

**Comment by drakkan** [comment]
Thanks for your suggestion, I'll consider goreleaser for the first stable release

**Comment by drakkan** [comment]
Hi,

I tested goreleaser locally using this file

```yaml
project_name: SFTPGo
release:
  github:
    owner: drakkan
    name: sftpgo
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- 
  main: .
  binary: sftpgo
  ldflags:
    - -s -w -X github.com/drakkan/sftpgo/utils.version={{.Version}} -X github.com/drakkan/sftpgo/utils.commit={{.ShortCommit}} -X github.com/drakkan/sftpgo/utils.date={{.Date}}
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- 
  replacements:
    darwin: macOS 
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - sftpgo.json
    - scripts/*
    - samples/*
    - README.md
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_sha256_checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-dev-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
```

it seems to build fine but the generated executable does not work, 

I get this self explaining error:

```
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

GoReleaser does not support CGO:

https://goreleaser.com/cgo/

Anyway I tryed to set  `CGO_ENABLED=1` in `.goreleaser.yml` and I was able to compile for Linux, since I'm on Linux and I have gcc installed but the building for macOS and windows failed (I have no cross compiler installed). I could do separate builds for Linux, macOS and windows but this way GoReleaser is not so useful, this can be manually accomplished simply using `go build`.

So GoReleaser support cannot happen now, sorry. We need to wait for a sqlite driver that does not require CGO or for CGO support in goreleaser
