### ISSUE TITLE
issue with defender 

### ISSUE THREAD

**Issue by killmasta93** [drakkan/sftpgo#1001]
Hi
I was wondering if someone could shed some light on the issue im having

1) currently i have installed with docker running 
```

docker run --name some-sftpgo \
    -p 8080:8090 \
    -p 2022:2022 \
    --mount type=bind,source=/jpg/sftpgodata,target=/srv/sftpgo \
    --mount type=bind,source=/jpg/sftpgohome,target=/var/lib/sftpgo \
    -e SFTPGO_HTTPD__BINDINGS__0__PORT=8090 \
    -d "drakkan/sftpgo:latest"
```
created a user and everything is working but when i try to brute force it does not block it automatically 
i also couldn't find on the WebGUI the option  

2) what possible to create a docker compose?

i tried something like this but not sure how to configure on the mount env

```
version: '3.3'
services:
    sftpgo:
        container_name: some-sftpgo
        ports:
            - '8080:8090'
            - '2022:2022'
        environment:
            - SFTPGO_HTTPD__BINDINGS__0__PORT=8090
        image: drakkan/sftpgo:latest
```
