### ISSUE TITLE
Add an "instance_id" field in event sent by common.actions.hook

### ISSUE THREAD

**Issue by StephaneBunel** [drakkan/sftpgo#1039]
Context:
I have multiple sftpgo server running (same host or remote).
Each one is configured to send the fs events (using common.actions.hook) to a web service endpoint.
Works fine.
Behind my web service, scripts need to connect back to the sftpgo server to handle file remotely (using virtual path).

Question:
From event point of view, how can I identify from which sftpgo instance the event is coming from ?

Suggestion:
Add an instance_id (user definable) field in event.

**Comment by drakkan** [comment]
You can add a custom HTTP header. 

Closing according to the [support policy](https://github.com/drakkan/sftpgo#support-policy)

**Comment by StephaneBunel** [comment]
As a workaround it is possible to add query parameters to hook.

```yaml
common:
  actions:
    execute_on: [ "upload" ]
    hook: http://endpoint.webhook.tld?instance_id=XXX
```
