### ISSUE TITLE
Rclone not working

### ISSUE THREAD

**Issue by grugel-maintro** [drakkan/sftpgo#1042]
Try to use sftpgo with rclone but get the following error. Does seem to be a problem with the ssh server setup by sftpgo. Use the docker-container on arm64 (raspberry pi):

`NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain`

use the following docker-compose to setup sftpgo: 
```
version: '3.6'

services:
  sftpgo:
    image: drakkan/sftpgo:alpine-slim
    container_name: sftpgo
    volumes:
      - ./data/sftpgodata:/srv/sftpgo
      - ./data/sftpgohome:/var/lib/sftpgo
    ports:
      - 8080:8080
      - 2022:2022

```
