### ISSUE TITLE
docker-compose example

### ISSUE THREAD

**Issue by cnwangfei** [drakkan/sftpgo#1060]
[https://larsl.dev/docker-compose/sftpgo](url)

docker-compose.yml
```yml
version: '3.5'

services:
  sftpgo:
    image: drakkan/sftpgo:alpine
    ports:
      - '8080:8080'
      - '2022:2022'
      - '2121:2121'
      - '50000-50100:50000-50100'
    env_file: sftpgo.env
    volumes:
      - ./data/sftpgo_data:/srv/sftpgo
      - ./data/sftpgo_home:/var/lib/sftpgo
      - ./data/sftpgo_certs:/certs:ro
```
sftpgo.env.example
```
SFTPGO_FTPD__BINDINGS__0__PORT=2121
SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=192.168.1.2
SFTPGO_FTPD__BINDINGS__0__TLS_MODE=1
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_FILE=/certs/fullchain.pem
SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_KEY_FILE=/certs/key.pem

SFTPGO_HTTPD__BINDINGS__0__ENABLE_HTTPS=1
SFTPGO_HTTPD__BINDINGS__0__CERTIFICATE_FILE=/certs/fullchain.pem
SFTPGO_HTTPD__BINDINGS__0__CERTIFICATE_KEY_FILE=/certs/key.pem
```
