### ISSUE TITLE
Docker compose cannot find data provider

### ISSUE THREAD

**Issue by Irvingouj** [drakkan/sftpgo#1197]
```
version: '3'
services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: irving-sftpgo
    user: "1100:1100"
    ports:
      - "8080:8080"
      - "2022:2022"
      - "2121:2121"
      - "10080:10080"
    volumes:
      - "${PWD}/data:/srv/sftpgo"
      - "${PWD}/config:/var/lib/sftpgo"
    restart: always
``` 

here's the log 
```
irving-sftpgo  | {"level":"debug","time":"2023-02-19T15:35:58.600","sender":"dataprovider","message":"absolute backup path \"/srv/sftpgo/backups\""}
irving-sftpgo  | {"level":"debug","time":"2023-02-19T15:35:58.600","sender":"dataprovider_sqlite","message":"sqlite database handle created, connection string: \"file:sftpgo.db?cache=shared&_foreign_keys=1\""}
irving-sftpgo  | {"level":"error","time":"2023-02-19T15:35:58.600","sender":"dataprovider_sqlite","message":"error preparing database query \"SELECT version from schema_version LIMIT 1\": unable to open database file: no such file or directory"}
irving-sftpgo  | {"level":"info","time":"2023-02-19T15:35:58.600","sender":"dataprovider_sqlite","message":"creating initial database schema, version 19"}
irving-sftpgo  | {"level":"error","time":"2023-02-19T15:35:58.601","sender":"dataprovider_sqlite","message":"error preparing database query \"SELECT version from schema_version LIMIT 1\": unable to open database file: no such file or directory"}
irving-sftpgo  | {"level":"error","time":"2023-02-19T15:35:58.601","sender":"dataprovider_sqlite","message":"Unable to initialize data provider: unable to open database file: no such file or directory"}
irving-sftpgo  | {"level":"error","time":"2023-02-19T15:35:58.601","sender":"service","message":"error initializing data provider: unable to open database file: no such file or directory"}
```

How do I specify the data-provider in the docker-compose file? thanks a lot, I will up date the documentation corresbondingly

**Comment by Irvingouj** [comment]
nvm

**Comment by Haprog** [comment]
I have the same issue trying to run with podman-compose. File permissions seem correct on the provided bind mounts but I can't figure out why it fails with this.

**Comment by nkay08** [comment]
> I have the same issue trying to run with podman-compose. File permissions seem correct on the provided bind mounts but I can't figure out why it fails with this.

Same here. I want to run sftpgo rootless via podman.
I checked all file and folder permissions and it still does not work.

**Comment by geekyouth** [comment]
```

services:
  # https://blog.csdn.net/networken/article/details/133963932
  sftpgo:
    image: drakkan/sftpgo:v2.5.4
    hostname: sftpgo
    container_name: sftpgo-dev
    user: root # 否则 ubuntu 启动闪退
    ports:
      - 8254:8080 # webui
      - 2022:2022 # sftp
      - 21:2121 # ftp
      - 50000-50010:50000-50010
      - 8090:8090 # webdav
    volumes:
      - ./_docker-data/sftpgo/data:/srv/sftpgo
      - ./_docker-data/sftpgo/home:/var/lib/sftpgo
    environment:
      TZ: Asia/Shanghai
      SFTPGO_HTTPD__BINDINGS__0__PORT: 8080
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 8090
      SFTPGO_FTPD__BINDINGS__0__PORT: 2121
      SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP: ${PASSIVE_IP:?}
      SFTPGO_FTPD__PASSIVE_PORT_RANGE__START: 50000
      SFTPGO_FTPD__PASSIVE_PORT_RANGE__END: 50010
      SFTPGO_GRACE_TIME: 32
    restart: unless-stopped

```

**Comment by fleimgruber** [comment]
> nvm

@Irvingouj seeing a similar issue, it would be great if you could share how you solved the issue, thanks!

**Comment by Haprog** [comment]
I got mine working but it was a while ago and I'm not sure if I did anything else except fix file permissions. So I'm running with rootless Podman using podman-compose.

This is my config:
```yml
version: "3"
services:
  sftpgo:
    image: drakkan/sftpgo:alpine
    container_name: sftpgo
    volumes:
      - /home/haprog/containers/sftpgo-data:/srv/sftpgo
      - /home/haprog/containers/sftpgo-home:/var/lib/sftpgo
    ports:
      - 8080:8080
      - 2022:2022
```

And these are the permissions on the data volumes from my host OS:
```ls
drwxr-xr-x 3 100999 100999 4,0K 2023-05-29 23:08 sftpgo-data/
drwxr-xr-x 2 100999 100999 4,0K 2024-01-30 19:54 sftpgo-home/
```

I think the trick was to set folder owner and group user IDs on host OS to 100999, this makes it map the namespace so that this will be owned by the `sftpgo` (1000) user inside the container. I'm not very familiar with this mapping yet, but this works for me.
