### ISSUE TITLE
Missing Folders

### ISSUE THREAD

**Issue by wassereimer86** [drakkan/sftpgo#1260]
Hi,

I wanted to test SFTPGo and have a problem that I can't solve the last days.

I'm using docker-compose on an Unraid Server 6.12.0-rc2 to start the container:

```
  sftpgo:
    container_name: "sftpgo"
    user: "99:100"
    environment:
      - "TZ=Europe/Berlin"
    hostname: "sftpgo"
    image: "drakkan/sftpgo:latest"
    networks:
      - "docker"
    ports:
      - "8120:8080/tcp"
      - "9579:2022/tcp"
    restart: "always"
    volumes:
      - "/mnt:/srv/sftpgo"
      - "sftpgo_home:/var/lib/sftpgo"
```

The problem is that the folders inside of `/mnt` are not visible via sftp. I originally wanted to use a directory inside `/mnt` but then I get errors when I try to connect. To test, I even tried giving the `/mnt` directory the same ownership (99:100), but I always retrieve an empty folder.

The home-dir of the user is set to `/mnt` because if I set `/` I land in the root directory (above mnt/). But even if i change into it, the folder is empty.

I also tried multiple client. FileZilla and WinSCP.

What am I missing or is there a bug?

Best regards
