### ISSUE TITLE
Java client TLS 1.3 error 550 (file transfert)

### ISSUE THREAD

**Issue by Anasme** [drakkan/sftpgo#1264]
Hello,

We are using sftpgo thought docker image:  drakkan/sftpgo:v2.2.3 and we experienced a curious error when tryin to transfert a file with a java client (version 11 ) using TLS 1.3 :

`java.io.IOException: Failed to write to '/file.file'. Server replied with: 550 Issue during transfer: remote error: tls: user canceled`

- server config:
```
docker_sftpgo_name: sftpgo
docker_sftpgo_image: drakkan/sftpgo:v2.2.3
docker_sftpgo_pull:
docker_sftpgo_expose:
docker_sftpgo_ports:
  - "443:443"
  - "990:2121"
  - "50000-50100:50000-50100"
docker_sftpgo_user:
docker_sftpgo_env:
  SFTPGO_COMMON__DEFENDER__ENABLED: "true"
  SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN: "true"
  SFTPGO_DEFAULT_ADMIN_USERNAME: xx
  SFTPGO_DEFAULT_ADMIN_PASSWORD: "{{ sftp_admin_password }}"
  SFTPGO_SFTPD__BINDINGS__0__PORT: "0"
  SFTPGO_FTPD__BINDINGS__0__PORT: "2121"
  SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP: "{{ ftps_external_ip }}"
  SFTPGO_FTPD__BINDINGS__0__TLS_MODE: "1"
  SFTPGO_FTPD__CERTIFICATE_FILE: /etc/sftpgo/ssl/{{ ftps_domain }}.crt
  SFTPGO_FTPD__CERTIFICATE_KEY_FILE: /etc/sftpgo/ssl/{{ ftps_domain }}.key 
  SFTPGO_HTTPD__BINDINGS__0__ENABLE_HTTPS: "true"
  SFTPGO_HTTPD__BINDINGS__0__PORT: "443"
  SFTPGO_HTTPD__CERTIFICATE_FILE: /etc/sftpgo/ssl/{{ ftps_domain }}.crt
  SFTPGO_HTTPD__CERTIFICATE_KEY_FILE: /etc/sftpgo/ssl/{{ ftps_domain }}.key 
  SFTPGO_DATA_PROVIDER__AUTO_BACKUP__0__ENABLED: "true"
  SFTPGO_DATA_PROVIDER__AUTO_BACKUP__0__HOUR: "*"
  SFTPGO_DATA_PROVIDER__AUTO_BACKUP__0__DAY_OF_WEEK: "*"
```
  
  Using tls 1.2 solve the problem but I don't understand atm why 1.3 make this error.
  
  Any idea?
