### ISSUE TITLE
Allow configure `/web/admin` and `/web/client`

### ISSUE THREAD

**Issue by vnghia** [drakkan/sftpgo#1267]
Currently, I see the `/web/admin` and `/web/client` are hardcoded. In my case, I have already hosted my admin web and client web on a separate subdomain so I would like to remove these two prefixes. I can send a PR if you think this feature is good. Thank you for your wonderful product !

**Comment by drakkan** [comment]
Hello, this can be done but could create unforeseen problems, for example if we allow to set both web client and web admin base path to `/` we'll have conflicting rules: `/web/client/login` and `/web/admin/login` will become `/login`. 
The prefix is also used internally to distinguish requests for the WebClient, the WebAdmin and REST APIs and to reply with appropriate pages/responses (for example for a not found url we reply with a json response for REST API requests and with an appropriate page for WebUIs). 

This is a potential breaking change, If you want to send a PR I'll try to review after releasing v2.5.

Maybe you can achieve the same with some URL rewrite magic in your web server configuration.

**Comment by vnghia** [comment]
Thank for your fast reply. I will see if I can do in this case !

**Comment by vnghia** [comment]
After playing with the URL rewrite magic for a while I gave up because it seems to break the authetication endpoint (`twofactor`). If you think it is worth implementing this feature from `sftpgo` side, I could give it a try, if no I think we can close this issue for now.

**Comment by drakkan** [comment]
Can you please share what you have tried? I'd like to take a look when I have some free time. Thank you

**Comment by vnghia** [comment]
Ah actually, I were able to make it working. I will attach my detailed configuration tomorrow but basically I am using Traefik as a reverse proxy server and I did 3 things:
- Rewrite html from `/web/admin/` to `/`.
- Add redirection rule as well as rewrite redirection header if presented.
- The most tricky part is rewriting the path of the cookie to point to `/` instead of `/web/client/`. I have to write my own traefik for this purpose (of course public).

**Comment by drakkan** [comment]
I see that cookie path rewriting doesn't seem to be supported in Traefik (I don't know Traefik very well), while it should work in [NGINX](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path)/[Apache](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreversecookiepath), I'll consider simplifying the cookie part on the SFTPGo side

**Comment by vnghia** [comment]
well you do not need anymore. I just wrote a plugin here. https://plugins.traefik.io/plugins/64447c14cb56144f9bdcb475/cookie-path-rewrite-plugin

**Comment by vnghia** [comment]
In addition, I think it is best to keep the cookie part hardcoded as the `/web/admin` because that will cause some security threats if the path is `/web/admin` but the cookie path is `/`.

**Comment by vnghia** [comment]
So below is my configuration for `traefik`.
Static configuration:
```yaml
experimental:
  plugins:
    rewrite-body:
      moduleName: "github.com/packruler/rewrite-body"
      version: "v1.2.0"
    rewrite-cookie-path:
      modulename: "github.com/vnghia/traefik-plugin-rewrite-cookie-path"
      version: "v0.0.1"
```

Dynamic configuration:
```yaml
  middlewares:
    set-cookie-path-as-root-admin:
      plugin:
        rewrite-cookie-path:
          rewrites:
            - name: "jwt"
              regex: "/web/admin"
              replacement: "/"
    rewrite-redirect-admin:
      redirectRegex:
        regex: "/web/admin/(.*)"
        replacement: "/$1"
    rewrite-path-request-admin:
      replacePathRegex:
        regex: "${replace_admin_path_regex}"
        replacement: "/web/admin/$1"
    rewrite-path-response-admin:
      plugin:
        rewrite-body:
          lastModified: true
          rewrites:
            - regex: "/web/admin/"
              replacement: "/"
          monitoring:
            methods:
              - GET
              - HEAD
              - POST
              - PUT
            types:
              - text/html
              - text/javascript
    set-cookie-path-as-root-client:
      plugin:
        rewrite-cookie-path:
          rewrites:
            - name: "jwt"
              regex: "/web/client"
              replacement: "/"
    rewrite-redirect-client:
      redirectRegex:
        regex: "/web/client/(.*)"
        replacement: "/$1"
    rewrite-path-request-client:
      replacePathRegex:
        regex: "${replace_client_path_regex}"
        replacement: "/web/client/$1"
    rewrite-path-response-client:
      plugin:
        rewrite-body:
          lastModified: true
          rewrites:
            - regex: "/web/client/"
              replacement: "/"
          monitoring:
            methods:
              - GET
              - HEAD
              - POST
              - PUT
            types:
              - text/html
              - text/javascript
```

Let me explain it a little bit:
- `set-cookie-path-as-root-admin`: change the cookie path from `/web/admin` to `/`.
- `rewrite-redirect-admin`: when the browser go to `/web/admin/$1` it will be redirected to `/$1`.
- `rewrite-path-request-client`: After the browser go and send a request to `/$1`, `traefik` will forward that request to our `sftpgo`. Since the real path is still `/web/admin/$1` we have to add a prefix to `traefik`. However, not **all** requests are behind the prefix `/web/admin` for example `/static/*` so we only rewrite paths in this file https://raw.githubusercontent.com/drakkan/sftpgo/master/internal/httpd/httpd.go. We could get the regex parameters by running this script:
```python
from urllib.request import urlopen
import re
import json

sftpgo_version = json.loads(input())["sftpgo_version"]

url = f"https://raw.githubusercontent.com/drakkan/sftpgo/{sftpgo_version}/internal/httpd/httpd.go"
with urlopen(url) as response:
    content: str = response.read().decode("utf-8")
    output = {}
    output["replace_admin_path_regex"] = "^/({})".format(
        "|".join(re.findall(r'"/web/admin/(.*)"', content))
    )
    output["replace_client_path_regex"] = "^/({})".format(
        "|".join(re.findall(r'"/web/client/(.*)"', content))
    )
    print(json.dumps(output))
```
- `rewrite-path-response-admin`: rewrite `/web/admin/` in `html` and `js` file to `/`.
