### ISSUE TITLE
Feature: dynamic confog based on docker labels, like traefik is doing it for http

### ISSUE THREAD

**Issue by gmuellerinform** [drakkan/sftpgo#1269]
I'd like to setup a vhost like system, where users can use sftp to update the files in their lamp containers. sftpgo would be an awesome solution.
Traefik docker provider: https://doc.traefik.io/traefik/providers/docker/

Example would be:
```
version: "3"
services:
  my-container:
    # ...
    labels:
      - sftpgo.authorized_key=<pub key>
      - sftpgo.volume=mydata
      - sftpgo.folder=/html
```
