### ISSUE TITLE
problem with invalid s3 certificate

### ISSUE THREAD

**Issue by tobiasz-gleba** [drakkan/sftpgo#1418]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hi, I have a problem with a private kubernetes connection via https, because the minio operator issess own CA, and I'm not able to ignore not valid SSL connection from the Sftpgo perspective. Can we add a toggle to ignore certificate validation?

### Steps to reproduce

1. Install own Minio operator instance
2. Try to connect connect via `*.svc.cluster.local`

### Expected behavior

I should be able to do something like "Ignore not valid SSL certificate"

### SFTPGo version

latest

### Data provider

s3

### Installation method

Community Docker image

### Configuration

```yaml
    data_provider:
      driver: mysql
      name: mysql_innodbcluster
      host: mysql-innodbcluster.mysql-operator.svc.cluster.local # host: sftpgo.mariadb-system.svc.cluster.local
      port: 3306
      username: "${db_username}"
      password: "${db_password}"
      sslmode: 0
      # sql_tables_prefix: sftpgo-
    httpd: 
      folder_prefix: /files
      hide_support_link: true
      bindings:
        port: 80
        enable_web_admin: ${if_dev_env}
        enable_web_client: ${if_dev_env}
```

### Relevant log output

```shell
{"level":"debug","time":"2023-09-14T23:02:52.512","sender":"HTTP","connection_id":"HTTP_ck1p26v1172s73djaff0","message":"error listing directory: operation error S3: ListObjectsV2, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get \"https://minio.minio-system.svc.cluster.local/data?delimiter=%2F&list-type=2&prefix=\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)
