### ISSUE TITLE
[Bug]: modifying sftp folder removes private key when saving

### ISSUE THREAD

**Issue by Saper140** [drakkan/sftpgo#1433]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I have found that if you setup a SFTP folder and set the private key it works great. However, when you modify the SFTP folder you have to re-enter the private key because the key gets replaced with [**REDACTED**]. When saving after modifying the key gets set to the [**REDACTED**]

Hopefully this makes sense. I'm new to reporting bugs so please let me know how I can improve. Thank you

### Steps to reproduce

1. Add a new folder
2. Select **SFTP** Storage type
3. Fill information and set the **Private Key**
4. Save settings.
5. Subbmit
6. Should now work when accessing the new folder.
7. Modify the folder and its settings
8. subbmit
9. key user wont match any longer

### Expected behavior

edit folder settings subbit changes, user and key should still work

### SFTPGo version

2.5.4

### Data provider

mysql

### Installation method

Community Docker image

### Configuration

docker-compose

```yaml
services:

  sftpgo:
    image: drakkan/sftpgo:v2-alpine
    user: ${USER}:${GROUP}
    restart: always
    container_name: sftpgo
    depends_on:
      - sftp_mysql
    ports:
      # - 8888:8080 # HTTP
      - 2134:2022 # SFTP
      # - 8443:443 # HTTPS
      # - 5007:5007 # WEBDAV
    environment:
      # These are the settings to access your db
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 5007
      SFTPGO_DATA_PROVIDER__DRIVER: mysql
      SFTPGO_DATA_PROVIDER__NAME: ${DB_NAME}
      SFTPGO_DATA_PROVIDER__HOST: sftp_mysql
      SFTPGO_DATA_PROVIDER__PORT: 3306
      SFTPGO_DATA_PROVIDER__USERNAME: ${DB_USER}
      SFTPGO_DATA_PROVIDER__PASSWORD: ${DB_PASS}
      SFTPGO_COMMON_DEFENDER__ENABLED: true
      SFTPGO_COMMON_DEFENDER__BAN_TIME: 15
      SFTPGO_COMMON_DEFENDER__BAN_TIME_INCREMENT: 100
      SFTPGO_COMMON_DEFENDER__THRESHOLD: 5
      SFTPGO_COMMON_DEFENDER__OBSERVATION_TIME: 15
    volumes:
      - ./sftpgo/data:/srv/sftpgo
      - /nvme/jellyfin/media:/media
    networks:
      - sftpgo-net

  sftp_mysql:
    image: mysql:latest
    restart: always
    hostname: sftp_mysql
    container_name: sftp_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - sftpgo-net

networks:
  sftpgo-net:
    name: sftpgo-net
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)
