### ISSUE TITLE
[Bug]: User directory is not deleted after deleting the user itself

### ISSUE THREAD

**Issue by goldmont** [drakkan/sftpgo#1439]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hi,

I hope that it's not my fault due to a misconfiguration. Users directories under `/srv/sftpgo/data` are kept even after deleting the users themselves. Is there a parameter that needs to be set? Thank you in advance.

### Steps to reproduce

1. Create a user
2. Login using Filezilla
3. Delete user

### Expected behavior

I expect that SFTPGo deletes the user directory

### SFTPGo version

2.5.4

### Data provider

Mounted folder

### Installation method

Community Docker image

### Configuration

Basic configuration:
```yaml
sftp:
  container_name: sftp
  image: drakkan/sftpgo:v2.5.4
  restart: unless-stopped
  volumes:
    - ./data/home:/var/lib/sftpgo
    - ./data/users:/srv/sftpgo/data
  ports:
    - '2022:2022'
  networks:
    - proxy_network
    - sftp_network
  labels:
    - traefik.enable=true
    - traefik.http.services.sftp.loadbalancer.server.port=8080
    - traefik.http.routers.sftp.rule=Host(`sftp.lab.test`)
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)
