### ISSUE TITLE
Loading passwords and other confidential settings from files (1 file = 1 setting)

### ISSUE THREAD

**Issue by patrickap** [drakkan/sftpgo#1453]
### Is your feature request related to a problem? Please describe.

It would be great if SFTPGo would support Docker Secrets for connecting to databases. Currently I set up a separate entrypoint in Docker Compose to read the secrets and set the appropriate variables. I doubt that this is safe.

```yml
...
services:
  sftpgo:
    image: drakkan/sftpgo:v2.5.4-alpine
    entrypoint: ["entrypoint.sh"]
    command: ["sftpgo", "serve"]
    environment:
      - SFTPGO_DATA_PROVIDER__DRIVER=postgresql
      - SFTPGO_DATA_PROVIDER__NAME=sftpgo-db
      - SFTPGO_DATA_PROVIDER__HOST=sftpgo-postgres
      - SFTPGO_DATA_PROVIDER__PORT=5432
      - SFTPGO_DATA_PROVIDER__USERNAME_FILE=/run/secrets/postgres-user
      - SFTPGO_DATA_PROVIDER__PASSWORD_FILE=/run/secrets/postgres-password
    restart: always
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - sftpgo-data:/srv/sftpgo/data
      - sftpgo-config:/var/lib/sftpgo
    secrets:
      - postgres-user
      - postgres-password
...
```

entrypoint.sh
```bash
#!/bin/sh

if [ "$SFTPGO_DATA_PROVIDER__USERNAME_FILE" ]; then
 	export SFTPGO_DATA_PROVIDER__USERNAME=$(cat $SFTPGO_DATA_PROVIDER__USERNAME_FILE)
 	unset SFTPGO_DATA_PROVIDER__USERNAME_FILE
fi

if [ "$SFTPGO_DATA_PROVIDER__PASSWORD_FILE" ]; then
 	export SFTPGO_DATA_PROVIDER__PASSWORD=$(cat $SFTPGO_DATA_PROVIDER__PASSWORD_FILE)
 	unset SFTPGO_DATA_PROVIDER__PASSWORD_FILE
fi

exec "$@"
```

Would this be something that SFTPGo itself could support? I was just about to create a PR, but when looking through the codebase I didn't see where I had to make adjustments.

### Describe the solution you'd like

See above

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
I think you can mount your secrets as env files in the env.d directory relative to your config dir (`/var/lib/sftpgo` in Docker). You can also define the whole config file as secret

**Comment by patrickap** [comment]
Thanks for the reply. You are correct. I saw this mentioned in the documentation. However, defining this env file as a secret would still require to add a separate secret for the password and user, as PostgreSQL expects it that way. This would result in no single source of truth.

**Comment by drakkan** [comment]
Not sure to understad, I mean defining a secret with content like this (untested)

```
SFTPGO_DATA_PROVIDER__USERNAME=user
SFTPGO_DATA_PROVIDER__PASSWORD=pass
```

and mounting it in the env.d directory. Please clarify with an example if this does not answer your question. Thanks

**Comment by patrickap** [comment]
To my knowledge Docker secrets store only a single value not key-value pairs. In the case of Postgres and other containers they expect each value individually. Example:

postgres-user.txt
```txt
user
```

postgres-password.txt
```txt
pass
```

docker-compose.yml
```yml
services:
 postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    restart: always
    secrets:
      - postgres-user
      - postgres-password

secrets:
  postgres-user:
    file: ./secrets/postgres-user.txt
  postgres-password:
    file: ./secrets/postgres-password.txt
```

**Comment by drakkan** [comment]
```
$ cat envfile 
SFTPGO_COMMON__DEFENDER__ENABLED=1
SFTPGO_DATA_PROVIDER__DELAYED_QUOTA_UPDATE=120
```


```
services:
  sftpgo:
    container_name: sftpgo
    ....
    secrets:
      - source: sftpgo_env
        target: /var/lib/sftpgo/env.d/sftpgo.env

secrets:
    sftpgo_env:
        file: ./envfile
```
