### ISSUE TITLE
Add documentation for a "blessed" docker-compose.yml and traefik

### ISSUE THREAD

**Issue by fleimgruber** [drakkan/sftpgo#1508]
### Is your feature request related to a problem? Please describe.

I am struggling to set up sftpgo as a Docker container behind traefik in a docker compose deployment.

### Describe the solution you'd like

There is an official docker-compose.yml file with instructions on setup.

### Describe alternatives you've considered

I found https://thad.getterman.org/articles/file-traefik/ and https://swag.industries/simple-webdav-server-with-sftpgo-docker-and/ but the former goes into too much detail and the latter is missing the admin setup.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional context

This is my attempt at a minimal docker-compose.yml that we could iterate on:

```yaml
version: '3.8'

volumes:
  traefik-ssl-certs:

networks:
  mynetwork:
    driver: bridge

services:
  traefik:
    image: "traefik:v2.10"
    # container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.bufferingsize=50"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # TLS
      - "--certificatesresolvers.production.acme.tlschallenge=true"
      - "--certificatesresolvers.production.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.production.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.production.acme.email=${LETS_ENCRYPT_EMAIL}"

    ports:
      - "80:80"
      - "443:443"
      - "8000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-ssl-certs:/letsencrypt"
    networks:
      - mynetwork

  webdav:
    image: drakkan/sftpgo:v2.5
    user: root
    volumes:
      - ./_docker-data/sftpgo/data:/srv/sftpgo
      - ./_docker-data/sftpgo/home:/var/lib/sftpgo
    environment:
      # This env var enables webdav integration and specifies its port binding
      SFTPGO_HTTPD__BINDINGS__0__PORT: '8082'
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: '8090'
      SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN: 1
      SFTPGO_DEFAULT_ADMIN_USERNAME: admin
      SFTPGO_DEFAULT_ADMIN_PASSWORD: ${SFTPGO_ADMIN_PASSWORD}
    restart: always
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"

      # We need to route the port for webdav
      - "traefik.http.routers.webdav.entrypoints=websecure"
      - "traefik.http.services.webdav.loadbalancer.server.port=8090"
      - "traefik.http.routers.webdav.rule=Path(`/webdav`) || PathPrefix(`/webdav/`)"
      - "traefik.http.routers.webdav.tls=true"
      - "traefik.http.routers.webdav.tls.certresolver=production"
      - "traefik.http.routers.webdav.priority=2"
      - "traefik.http.routers.webdav.service=webdav"

      # And the port to access the UI
      - "traefik.http.routers.webdavui.entrypoints=websecure"
      - "traefik.http.services.webdavui.loadbalancer.server.port=8082"
      - "traefik.http.routers.webdavui.rule=Path(`/webdavui`) || PathPrefix(`/webdavui/`)"
      - "traefik.http.routers.webdavui.tls=true"
      - "traefik.http.routers.webdavui.tls.certresolver=production"
      - "traefik.http.routers.webdavui.priority=2"
      - "traefik.http.routers.webdavui.service=webdavui"
```

which seems to work, but https://DOMAIN/webdavui/web/admin/login returns a `{"message":"Not Found"}`. In the sftpgo logs I see:

```
2024-01-12T14:21:38.474 WRN sender=httpd local_addr=172.19.0.10:8082 method=GET proto=HTTP/1.1 remote_addr=172.19.0.5:51188 request_id=3714b49fc380/92BTMqfYLf-000022 uri=http://DOMAIN/webdavui/web/admin/login user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0 resp_status=404 resp_size=24 elapsed_ms=0
```

I am able to curl that URL and get a response from within the docker container after a `docker exec -it webdav-1 bash`.
