### ISSUE TITLE
[Bug]: branding does not work after upgrade (2.5 -> 2.6).

### ISSUE THREAD

**Issue by fauust** [drakkan/sftpgo#1639]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Branding is not working anymore after upgrade to the latest version (2.6).

### Steps to reproduce

1. Edit docker-compose.yml file and bump the version (`drakkan/sftpgo:v2.6-alpine`);
2. Restart container (docker-compose down && docker-compose up -d`);
3. Reload admin/client page in browser;
4. The branding logo is not present anymore.

### Expected behavior

The logo is still present.

### SFTPGo version

drakkan/sftpgo:v2.6-alpine

### Data provider

local

### Installation method

Community Docker image

### Configuration

```yaml
  ---
  version: "3.7"
  services:
    sftpgo:
      image: drakkan/sftpgo:v2.6-alpine
      restart: unless-stopped
      container_name: sftpgo
      hostname: sftpgo
[...]
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__NAME=MariaDB SFTPGo WebAdmin
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_ADMIN__LOGIN_IMAGE_PATH=/branding/mdbf_logo.png
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__NAME=MariaDB SFTPGo WebClient
      - SFTPGO_HTTPD__BINDINGS__0__BRANDING__WEB_CLIENT__LOGIN_IMAGE_PATH=/branding/mdbf_logo.png
[...]
    volumes:
      - /srv/sftpgo/data:/srv/sftpgo
      - /srv/sftpgo/branding:/usr/share/sftpgo/static/branding
      - /srv/sftpgo/config:/var/lib/sftpgo
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

The logo is present in the container image in `/usr/share/sftpgo/static/branding`. In the browser page source the logo is still token from `/static/img/logo.png`.
