### ISSUE TITLE
[Bug]: Getting error 404 while generating certificate using SFTPGo Web UI

### ISSUE THREAD

**Issue by sbdtu5498** [drakkan/sftpgo#1756]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I am getting an error 404 while trying to generate certificate using let's encrypt while using the server https://acme-v02.api.letsencrypt.org/directory. I was trying to generate the certificate using SFTPGo. I have attached the logs in the relevant section. Also we captured the tcpdump and analyzed it. On analyzing the captured.pcap using wireshark we found out this 

```
GET /.well-known/acme-challenge/gnDDjZiByBevvZxGFk1TIN_z-22N-RgSSPOobWyAjXM HTTP/1.1
Host: ftp.test.dataforsyningen.dk
User-Agent: Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org/)
Accept: /
Accept-Encoding: gzip
Connection: close

HTTP/1.1 404 Not Found
Content-Type: application/json
Server: SFTPGo/2.6.2
Date: Mon, 09 Sep 2024 12:19:29 GMT
Content-Length: 24
Connection: close

{"message":"Not Found"}
```

Please take a look into this.

### Steps to reproduce

1. Setup the SFTPGo in docker container using a compose file like this.
2. Use Web UI to navigate to 'Server Manager' section and then to 'Configurations' section. 
3. In it, use 'ACME' section and fill it up with the relevant details and then save it generate certificate.

### Expected behavior

The certificate must have been created successfully.

### SFTPGo version

2.6.2

### Data provider

postgresql

### Installation method

Community Docker image

### Configuration

config

```
---
version: "3"
services:
  sftpgo:
    image: "drakkan/sftpgo:v2.6.2"
    user: root
    restart: unless-stopped
    ports:
      # HTTPS
      - 80:443
      # FTP
      - 21:2121
      # Passive FTP Range
      - 50000-50100:50000-50100
      # SFTP
      - 990:2022
      # WebDav
      - 5007:5007
    environment:
      SFTPGO_HTTPD__BINDINGS__0__PORT: 443
      SFTPGO_FTPD__BINDINGS__0__PORT: 2121
      SFTPGO_FTP__PASSIVE__PORT__RANGE: "50000-50100"
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 5007
      SFTPGO_DATA_PROVIDER__DRIVER: "postgresql"
      SFTPGO_DATA_PROVIDER__NAME: "ftp"
      SFTPGO_DATA_PROVIDER__HOST: "***"
      SFTPGO_DATA_PROVIDER__PORT: ***
      SFTPGO_DATA_PROVIDER__USERNAME: "***"
      SFTPGO_DATA_PROVIDER__PASSWORD: "***"
      SFTPGO_COMMON__DEFENDER__ENABLED: "false"
      SFTPGO_COMMON__DEFENDER__BAN_TIME: 15
      SFTPGO_COMMON__DEFENDER__BAN_TIME_INCREMENT: 100
      SFTPGO_COMMON__DEFENDER__THRESHOLD: 5
      SFTPGO_COMMON__DEFENDER__OBSERVATION_TIME: 15
      SFTPGO_DATA_PROVIDER__EXTERNAL_AUTH_HOOK: /srv/sftpgo/auth.sh
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/sftpgo:/srv/sftpgo
      - /local/data/webusers/ftp:/srv/sftpgo/ftp
      - /mnt/docker-volumes/certs:/var/lib/sftpgo/certs
```

### Relevant log output

```shell
sftpgo_1  | {"level":"debug","time":"2024-09-09T12:18:08.009","sender":"httpd","local_addr":"[Internal_IP]:8443","method":"GET","proto":"HTTP/1.1","remote_addr":"[Client_IP]:38022","request_id":"0b8b8a840bfd/xxxx","uri":"http://[domain]/web/admin/configs","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","resp_status":200,"resp_size":83648,"elapsed_ms":16}
sftpgo_1  | {"level":"debug","time":"2024-09-09T12:19:27.461","sender":"acme","message":"loading private key from file \"certs/acme-v02.api.letsencrypt.org/[email_redacted].key\", stat error: <nil>"}
sftpgo_1  | {"level":"debug","time":"2024-09-09T12:19:27.925","sender":"acme","message":"configuring HTTP-01 challenge, port 80"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:27.925","sender":"acme","message":"requesting certificates for domains [domain]"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:27.925","sender":"lego","message":"[INFO] [domain] acme: Obtaining bundled SAN certificate"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:28.484","sender":"lego","message":"[INFO] [domain] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxx"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:28.484","sender":"lego","message":"[INFO] [domain] acme: Could not find solver for: tls-alpn-01"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:28.484","sender":"lego","message":"[INFO] [domain] acme: use http-01 solver"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:28.484","sender":"lego","message":"[INFO] [domain] acme: Trying to solve HTTP-01"}
sftpgo_1  | {"level":"warn","time":"2024-09-09T12:19:29.105","sender":"httpd","local_addr":"[Internal_IP]:8443","method":"GET","proto":"HTTP/1.1","remote_addr":"[Validation_Server_IP]:55315","request_id":"0b8b8a840bfd/xxxx","uri":"http://[domain]/.well-known/acme-challenge/xxxxxx","user_agent":"Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)","resp_status":404,"resp_size":24,"elapsed_ms":0}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:35.438","sender":"lego","message":"[INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxx"}
sftpgo_1  | {"level":"error","time":"2024-09-09T12:19:35.600","sender":"acme","message":"unable to obtain certificates for domains [domain]: error: one or more domains had a problem:\n[domain] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: [External_IP]: Invalid response from http://[domain]/.well-known/acme-challenge/xxxxxx: 404\n"}
sftpgo_1  | {"level":"info","time":"2024-09-09T12:19:35.600","sender":"httpd","message":"unable to get ACME certificates: unable to obtain certificates: error: one or more domains had a problem:\n[domain] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: [External_IP]: Invalid response from http://[domain]/.well-known/acme-challenge/xxxxxx: 404\n"}
sftpgo_1  | {"level":"debug","time":"2024-09-09T12:19:35.603","sender":"httpd","local_addr":"[Internal_IP]:8443","method":"POST","proto":"HTTP/1.1","remote_addr":"[Client_IP]:51936","request_id":"0b8b8a840bfd/xxxx","uri":"http://[domain]/web/admin/configs","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","resp_status":200,"resp_size":83751,"elapsed_ms":8143}
```
```


### What are you using SFTPGo for?

Enterprise

### Additional info

_No response_
