### ISSUE TITLE
[Bug?]: Intermittent connections failing with "crypto/rsa: verification error"

### ISSUE THREAD

**Issue by dtabata** [drakkan/sftpgo#1826]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Here is a quote from [#1750](https://github.com/drakkan/sftpgo/issues/1750)

ーーーーーーーーーーーーーーーーーーーーーーー
We see intermittent instances of users failing SSH negotiation. They don't even get to authentication; the connection fails somewhere in the SSH handshake, and SFTPGo logs a "crypto/rsa: verification error" message. From the client's point of view, the connection drops unexpectedly.

This problem only occurs rarely (<1% of connections for affected users), and doesn't affect all users. I have not been able to identify any common factors among the users that are affected, and there's no sign that the server is hitting connection limits or is experiencing significant load. Users who experience the problem can reconnect successfully the next time they try, but it tends to trip up semi-automated transfers with poor error handling.
ーーーーーーーーーーーーーーーーーーーーーーー

### Steps to reproduce

1.Wait for users to connect a significant number of times.
2.Search the logs for "crypto/rsa: verification error"

### Expected behavior

User is able to negotiate the SSH connection and proceed to authentication.

### SFTPGo version

v2.5.6

### Data provider

PostgreSQL

### Installation method

Community Docker image

### Configuration

``` yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "..."
spec:
  ...
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "..."
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      ...
      containers:
        - name: "..."
          image: "drakkan/sftpgo:v2.5.6-slim"
          ports:
            ...
          resources:
            ...
          env:
            - name: "SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN"
              value: "true"
            - name: "SFTPGO_DEFAULT_ADMIN_USERNAME"
              value: "..."
            - name: "SFTPGO_DATA_PROVIDER__DRIVER"
              value: "postgresql"
            - name: "SFTPGO_DATA_PROVIDER__NAME"
              value: "..."
            - name: "SFTPGO_DATA_PROVIDER__HOST"
              value: "..."
            - name: "SFTPGO_DATA_PROVIDER__PORT"
              value: "5432"
            - name: "SFTPGO_DATA_PROVIDER__USERNAME"
              value: "..."
            - name: "SFTPGO_COMMON_DEFENDER__ENABLED"
              value: "true"
            - name: "SFTPGO_COMMON_DEFENDER__BAN_TIME"
              value: "15"
            - name: "SFTPGO_COMMON_DEFENDER__BAN_TIME_INCREMENT"
              value: "100"
            - name: "SFTPGO_COMMON_DEFENDER__THRESHOLD"
              value: "5"
            - name: "SFTPGO_COMMON_DEFENDER__OBSERVATION_TIME"
              value: "15"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/secrets/google/key.json"
            - name: "SFTPGO_HTTPD__BINDINGS__0__CLIENT_IP_PROXY_HEADER"
              value: "X-Forwarded-For"
            - name: SFTPGO_HTTPD__BINDINGS__0__CLIENT_IP_HEADER_DEPTH
              value: "0"
            - name: SFTPGO_HTTPD__BINDINGS__0__PROXY_ALLOWED
              value: "130.211.0.0/22,35.191.0.0/16"
          volumeMounts:
            ...
          readinessProbe:
            ...
```

### Relevant log output

```shell
failed to accept an incoming connection from ip "xxx.xxx.xxx.xxx": crypto/rsa: verification error
```

### What are you using SFTPGo for?

Medium business

### Additional info

Is a fix for this bug included in the Bug Fixes for v2.6.4?
![image](https://github.com/user-attachments/assets/791e106e-5749-435d-9643-d6371ba02706)
