### ISSUE TITLE
[Bug]: 2FA Not working from 1 day to another

### ISSUE THREAD

**Issue by tarreislam** [drakkan/sftpgo#1860]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Example of using an OTP-extension i use for everything. I have tried multiple others with the same result.
![image](https://github.com/user-attachments/assets/f48e7a52-de1c-4c91-9e08-f9f9e3791b80)

my docker-compose

```
version: "3.9"

services:
  sftpgo:
    image: drakkan/sftpgo:v2.6
    container_name: some-sftpgo
    user: "1000:1000"
    ports:
      - "8080:8080"
      - "2022:2022"
      - "2021:2021"
    volumes:
      - "/xxxxx:y"
      - "/xxxxx:y"
    restart: unless-stopped
```

### Steps to reproduce

1. Install sftpgo via docker-compose 
2. Wait x days
3. Try enable 2FA

### Expected behavior

2FA to work

### SFTPGo version

2.2

### Data provider

docker-compose

### Installation method

Community Docker image

### Configuration

default configuration.

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)
