### ISSUE TITLE
[Bug]: WebAdmin login fails in a multi-replica deployment

### ISSUE THREAD

**Issue by cfiehe** [drakkan/sftpgo#1895]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I am evaluating a multi-replica (active-active) setup of SFTPGo in Kubernetes (K3s) using the following Helm chart https://github.com/sftpgo/helm-chart. Unfortunately, when I try to log in with my predefined admin credentials, I encounter the error `The form token is not valid`. I tried the solution provided [here](https://github.com/drakkan/sftpgo/issues/1816), but it does not have any effect, login still fails. Based on the documentation I think it must be `SFTPGO_HTTPD__TOKEN_VALIDATION: '1'`, but that does also not solve the issue.

When I reduce the replica count from `3` to `1` login succeeds immediately. I assume that the servers cannot validate the token created by another one, but I cannot say it with certainty.

### Steps to reproduce

1. Setup a cluster of multiple SFTPGo servers e.g. use multiple replicas in Kubernetes
2. Add a loadbalancer in front of the cluster or use an ingress controller of your choice in Kubernetes
3. Try to login to the WebAdmin or create a admin user

### Expected behavior

Log in to the WebAdmin succeeds in a multi-replica setup.

### SFTPGo version

v2.6.5

### Data provider

PostgreSQL

### Installation method

Other

### Configuration

```
---
image:
  pullPolicy: Always
  tag: v2.6.5
replicaCount: 3
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
sftpd:
  enabled: true
ftpd:
  enabled: false
webdavd:
  enabled: false
httpd:
  enabled: true
ui:
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    hosts:
      - host: sftpgo-ui-t.mycompany.de
        paths:
          - path: /
            pathType: ImplementationSpecific
env:
  # Admin
  SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN: 'true'
  SFTPGO_DEFAULT_ADMIN_USERNAME: admin
  SFTPGO_DEFAULT_ADMIN_PASSWORD: admin
  # Database
  SFTPGO_DATA_PROVIDER__DRIVER: postgresql
  SFTPGO_DATA_PROVIDER__HOST: <SECRET>
  SFTPGO_DATA_PROVIDER__PORT: '5432'
  SFTPGO_DATA_PROVIDER__NAME: sftpgo_test
  SFTPGO_DATA_PROVIDER__USERNAME: sftpgo
  SFTPGO_DATA_PROVIDER__PASSWORD: <SECRET>
  # HTTP
  SFTPGO_HTTPD__TOKEN_VALIDATION: '1'
volumes:
  - name: sftpgo-data
    persistentVolumeClaim:
      claimName: sftpgo-data
volumeMounts:
  - name: sftpgo-data
    mountPath: /srv/sftpgo/
```
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-data
  namespace: sftpgo
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

### Relevant log output

```shell
2025-02-15T20:49:03.519981208+01:00 stdout F {"level":"debug","time":"2025-02-15T19:49:03.519","sender":"httpd","message":"error validating CSRF token \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiQ1NSRiIsIjEwLjIwOC4wLjgxIl0sImV4cCI6MTczOTY3MDUzNiwianRpIjoiY3VvZXZhMzZuNWVjNzNhN3RwaWciLCJuYmYiOjE3Mzk2NDg5MDZ9.esRGLttXMR6q5JTq-6EConJWN0Iodz2ChtKqE82ELag\": token is unauthorized"}
```

### What are you using SFTPGo for?

Enterprise

### Additional info

![Image](https://github.com/user-attachments/assets/0191dcce-af83-4d3b-a98f-bd1be0815b66)
