### ISSUE TITLE
[Bug]: sftp RSA Fingerprint keeps changing

### ISSUE THREAD

**Issue by deeztek** [drakkan/sftpgo#1906]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

RSA fingerprint for SFTP keeps changing on container restart. This becomes a huge problem on automated sftp transfers where the client expects to find same RSA key.

### Steps to reproduce

1. Restart container
2. Attempt to reconnect with sftp client
3. Get warning the fingerprint has changed

### Expected behavior

Expect the RSA fingerprint to stay the same.

### SFTPGo version

 2.6.5 d924811e

### Data provider

mysql

### Installation method

Community Docker image

### Configuration

 ```
environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 5007
      SFTPGO_FTPD__BINDINGS__0__PORT: 2121
      SFTPGO_FTPD__BINDINGS__0__TLS_MODE: 1
      SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_FILE: "/certs/cert.crt"
      SFTPGO_FTPD__BINDINGS__0__CERTIFICATE_KEY_FILE: "/certs/key.key"
      SFTPGO_FTPD__BINDINGS__0__MIN_TLS_VERSION: "12"
      SFTPGO_DATA_PROVIDER__DRIVER: "mysql"
      SFTPGO_DATA_PROVIDER__NAME: "sftpgo_db"
      SFTPGO_DATA_PROVIDER__HOST: 192.168.xxx.xxx
      SFTPGO_DATA_PROVIDER__PORT: 3306
      SFTPGO_DATA_PROVIDER__USERNAME: "mysql_user"
      SFTPGO_DATA_PROVIDER__PASSWORD: "mysql_password"
      SFTPGO_COMMON__DEFENDER__ENABLED: true
      SFTPGO_COMMON__DEFENDER__BAN_TIME: 15
      SFTPGO_COMMON__DEFENDER__BAN_TIME_INCREMENT: 100
      SFTPGO_COMMON__DEFENDER__THRESHOLD: 5
      SFTPGO_COMMON__DEFENDER__OBSERVATION_TIME: 15
```

### Relevant log output

```shell

```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)
