### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by fabiang** [drakkan/sftpgo#1923]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hello,

I'm currently trying to use multiple auth plugins with STPGo, to figure out if it's possible to have two different authentication methods. For testing-purposes I'm trying to configure the [sftpgo/sftpgo-plugin-auth](https://github.com/sftpgo/sftpgo-plugin-auth) plugin twice. If I'm trying to do this the authentication plugins are crashing.

My ultimate goal is write a auth plugin for SFTPGo.

### Steps to reproduce

1. configure the auth plugin twice
2. try to authenticate user
3. WebUI says "Invalid credentials, please retry"
4. plugin crash
5. remove second plugin
6. authentication is working

### Expected behavior

Support for multiple auth plugins

### SFTPGo version

2.6.6

### Data provider

postgresql

### Installation method

Community Docker image

### Configuration

Dockerfile:
```Dockerfile
ARG VERSION=v2.6
FROM drakkan/sftpgo:${VERSION}-plugins

# Assume a valid ldap config file
COPY ./config/ldap1.conf /etc/sftpgo/ldap1.conf
```

Docker-Compose:
```yaml
services:
  sftpgo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2022:2022"
      - "8080:8080"
    environment:
      SFTPGO_GRACE_TIME: 32
      SFTPGO_PLUGINS__0__TYPE: auth
      SFTPGO_PLUGINS__0__AUTH_OPTIONS__SCOPE: 5
      SFTPGO_PLUGINS__0__CMD: /usr/local/bin/sftpgo-plugin-auth
      SFTPGO_PLUGINS__0__ARGS: serve,--config-file,/etc/sftpgo/ldap1.conf
      SFTPGO_PLUGINS__0__AUTO_MTLS: 0
      SFTPGO_PLUGINS__1__TYPE: auth
      SFTPGO_PLUGINS__1__AUTH_OPTIONS__SCOPE: 5
      SFTPGO_PLUGINS__1__CMD: /usr/local/bin/sftpgo-plugin-auth
      SFTPGO_PLUGINS__1__ARGS: serve,--config-file,/etc/sftpgo/ldap1.conf
      SFTPGO_PLUGINS__1__AUTO_MTLS: 0
```

### Relevant log output

```shell
{"username":"","login_type":"password","protocol":"HTTP","error":"plugin auth error for user \"fabian.grutschus\": rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin1458069910: connect: connection refused\", elapsed: 79.031µs, auth scope: 1"}
{"sender":"plugins","message":"try to restart crashed auth plugin \"/usr/local/bin/sftpgo-plugin-auth\", idx: 0"}
{"sender":"plugins","message":"killed process /usr/local/bin/sftpgo-plugin-auth, pid 27, err <nil>"}
{"sender":"plugins","message":"create new auth plugin \"/usr/local/bin/sftpgo-plugin-auth\""}
{"sender":"plugins","message":"adding env vars with prefix \"SFTPGO_PLUGIN_AUTH_\" for plugin \"/usr/local/bin/sftpgo-plugin-auth\""}
{"sender":"plugins","message":"additional env vars for plugin \"/usr/local/bin/sftpgo-plugin-auth\": []"}
{"sender":"plugins.auth","path":"/usr/local/bin/sftpgo-plugin-auth","pid":"42","message":"plugin started"}
{"sender":"plugins.auth","plugin":"/usr/local/bin/sftpgo-plugin-auth","message":"waiting for RPC address"}
{"sender":"plugins.auth","plugin":"/usr/local/bin/sftpgo-plugin-auth","id":"27","error":"signal: killed","message":"plugin process exited"}
{"sender":"plugins.auth.stdio","err":"rpc error: code = Canceled desc = context canceled","message":"received EOF, stopping recv loop"}
{"sender":"plugins.auth.sftpgo-plugin-auth","message":"[INFO]  authenticator created: dial URLs=[\"<redacted>\"] base dn=\"<redacted>\""}
{"sender":"plugins.auth.sftpgo-plugin-auth","message":"[DEBUG] multi authenticator initialized: LDAP servers=1 cache size=100"}
{"sender":"plugins.auth","version":"1","message":"using plugin"}
{"sender":"plugins.auth.sftpgo-plugin-auth","address":"/tmp/plugin694026016","network":"unix","message":"plugin address"}
{"sender":"plugins.auth.stdio","message":"waiting for stdio data"}
```

### What are you using SFTPGo for?

Medium business
