### ISSUE TITLE
[Bug]: create_default_admin has no effect in v2.6.6 (memory data provider)

### ISSUE THREAD

**Issue by shapirus** [drakkan/sftpgo#1955]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

The `create_default_admin` setting has no apparent effect. Default admin doesn't get created.

### Steps to reproduce

1. Use the following k8s deployment manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sftpgo
        image: drakkan/sftpgo:v2.6.6
        env:
        - name: SFTPGO_DEFAULT_ADMIN_USERNAME
          value: "admin"
        - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
          value: "foobar"

        - name: SFTPGO_DATA_PROVIDER__DRIVER
          value: "memory"
        - name: SFTPGO_DATA_PROVIDER__UPDATE_MODE
          value: "0"
        - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
          value: "true"
```

2. Try to log in into the web UI using the specified credentials (admin/foobar)

3. The web UI says 'Invalid credentials, please retry' and the following messages appear in the log:

```
{"level":"warn","time":"2025-04-24T09:02:56.094","sender":"dataprovider_memory","message":"error authenticating user \"admin\": not found: username \"admin\" does not exist"}
{"level":"debug","time":"2025-04-24T09:02:56.094","sender":"connection_failed","client_ip":"127.0.0.1","username":"","login_type":"password","protocol":"HTTP","error":"not found: username \"admin\" does not exist"}
```

### Expected behavior

A default admin account with the specified credentials should have been created as described in the docs at https://docs.sftpgo.com/2.6/config-file/#data-provider

### SFTPGo version

2.6.6

### Data provider

memory

### Installation method

Community Docker image

### Configuration

As shown above.

### Relevant log output

```shell

```

### What are you using SFTPGo for?

Small business (3-person firm with file exchange?)
