### ISSUE TITLE
[Bug]: Misleading exception handling on input/output error during download

### ISSUE THREAD

**Issue by niklastanner** [drakkan/sftpgo#1962]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.

## Cause of my issue
I have a corrupt file on my SFTPGO server, which cannot be downloaded, neither via SFTP nor WebUI. It can also not be viewed using the WebUI. When viewing it (pressing the eye icon in the webui) the image loads endlessly while sftpgo closes the connection siltently.

## Why do I think there is a bug
I tried to download a folder using the WebUI. The ZIP download starts and the browser counts the Bytes. After a fixed amount of bytes the download stalls. After 13 seconds it fails with "Check internet connection". The reverse proxy logs that the connection has been closed by sftpgo and since no further information is available returns a 200 OK to the browser.

This is quite misleading as I was looking for a network issue here, but it seems that the input/output exception makes sftpgo to close the connection without further notice.

When downloading the file using SFTP the download starts, 1.8/5MB are downloaded, then the download stalls. After 20 seconds the inactive download is being aborted (not sure if by the server or the client, I didn't investigate further)

### Steps to reproduce

1. Get a corrupted file on the sftpgo server
2. Download the file using WebUI or FTP

### Expected behavior

I would assume that the connection would be closed with an error message so that my browser can tell me there is an error on the sftpgo side.

### SFTPGo version

2.6.6

### Data provider

Helm Chart default

### Installation method

Other

### Configuration

```
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

volumes:
  - name: configuration
    persistentVolumeClaim:
      claimName: sftpgo-config
  - name: data
    persistentVolumeClaim:
      claimName: sftpgo-data

volumeMounts:
  - mountPath: /var/lib/sftpgo
    name: configuration
  - mountPath: /srv/sftpgo/data
    name: data

config:
  data_provider:
    create_default_admin: true
    users_base_dir: /srv/sftpgo/data/homes

envVars:
  - name: SFTPGO_DEFAULT_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: sftpgo-creds
        key: username
  - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: sftpgo-creds
        key: password
  - name: SFTPGO_LOGIND_METHOD
    value:
  - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID
    value: "sftpgo"
  - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL
    value: "https://keycloak.example.com/realms/master"
  - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL
    value: "https://sftpgo.example.com"
  - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD
    value: "preferred_username"
  - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD
    value: "sftpgo_role"
  - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: sftpgo-creds
        key: oauth2-client-secret

ui:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    hosts:
      - host: sftpgo.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - sftpgo.example.com
```

### Relevant log output

```shell
{"level":"error","time":"2025-04-28T07:52:16.723","sender":"OIDC","connection_id":"OIDC_d07j6tdsuacc73c6tod0","message":"Unexpected error for transfer, path: \"/srv/sftpgo/data/media/images/P1310932.JPG\", error: \"read /srv/sftpgo/data/media/images/P1310932.JPG: input/output error\" bytes sent: 9183232, bytes received: 0 transfer running since 46648 ms"}
{"level":"error","time":"2025-04-28T07:52:16.724","sender":"Download","local_addr":"10.1.67.58:8080","remote_addr":"10.1.67.233:50662","elapsed_ms":46649,"size_bytes":9183232,"username":"niklas","file_path":"/srv/sftpgo/data/media/images/P1310932.JPG","connection_id":"OIDC_d07j6tdsuacc73c6tod0","protocol":"OIDC","error":"read /srv/sftpgo/data/media/images/P1310932.JPG: input/output error"}
{"level":"error","time":"2025-04-28T07:52:16.724","sender":"OIDC","connection_id":"OIDC_d07j6tdsuacc73c6tod0","message":"transfer error: read /srv/sftpgo/data/media/images/P1310932.JPG: input/output error, path: \"/srv/sftpgo/data/media/images/P1310932.JPG\""}
{"level":"debug","time":"2025-04-28T07:52:16.724","sender":"OIDC","connection_id":"OIDC_d07j6tdsuacc73c6tod0","message":"transfer removed, id: 36 active transfers: 0"}
{"level":"error","time":"2025-04-28T07:52:16.724","sender":"OIDC","connection_id":"OIDC_d07j6tdsuacc73c6tod0","message":"generic error: read /srv/sftpgo/data/media/images/P1310932.JPG: input/output error"}
{"level":"debug","time":"2025-04-28T07:52:16.724","sender":"OIDC","connection_id":"OIDC_d07j6tdsuacc73c6tod0","message":"connection removed, local address \"10.1.67.58:8080\", remote address \"10.1.67.233:50662\" close fs error: <nil>, num open connections: 0"}
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

### Additional info

Internet -> traefik (reverse proxy) -> sftpgo
traefik and sftpgo are running in a kubernetes cluster.
sftpgo is deployed using the helm chart `oci://ghcr.io/sftpgo/helm-charts` version `0.37.0`.
traefik has the default `websecure` port and additionally port 22 on TCP exposed.
