### ISSUE TITLE
[Bug]: SFTPGo moves partially uploaded file to user folder using atomic upload_mode

### ISSUE THREAD

**Issue by goldmont** [drakkan/sftpgo#1983]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Hi,

Using FTP service and atomic upload_mode, I double-checked the service to work properly. So, using the web interface, I've uploaded a file simulating a slow connection. I can see the temporary file in the correct folder but, as soon as I refresh the browser page while it's still uploading the file, SFTPGo moves the file from the temporary folder to the user folder. That's not the expected behavior. I expect SFTPGo to delete the partially uploaded file as the documentation states.

Any help?

### Expected behavior

I expect SFTPGo to delete the partially uploaded file.

### SFTPGo version

Latest 2.6.x

### Data provider

Local FTP service

### Installation method

Community Docker image

### Configuration

```yml
SFTPGO_COMMON__UPLOAD_MODE: 1
SFTPGO_COMMON__TEMP_PATH: /srv/sftpgo/tmp
SFTPGO_SFTPD__BINDINGS__0__PORT: 0
SFTPGO_FTPD__BINDINGS__0__PORT: 2121
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)
