### ISSUE TITLE
SFTPGO_LOADDATA_FROM 

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#216]
Firstly, great project. 

However i am a little confused regarding the use of SFTPGO_LOADDATA_FROM

In my instance i am supplying a users.json file which originates from the API data dump. Upon starting the service, supplying the SFTPGO_LOADDATA_FROM env var with the absolute path to the json file, does not load the users into the default sqlite db, should it? If not, when is one suppose to use SFTPGO_LOADDATA_FROM ?

**Comment by drakkan** [comment]
> Firstly, great project.
> 

thank you

> However i am a little confused regarding the use of SFTPGO_LOADDATA_FROM
> 
> In my instance i am supplying a users.json file which originates from the API data dump. Upon starting the service, supplying the SFTPGO_LOADDATA_FROM env var with the absolute path to the json file, does not load the users into the default sqlite db, should it? If not, when is one suppose to use SFTPGO_LOADDATA_FROM ?

it should work, please post the logs

**Comment by ryjogo** [comment]
logs: https://pastebin.com/N4tyUMqP

my env vars are:
```
          env:
            - name: SFTPGO_SFTPD__BIND_PORT
              value: "2022"
            - name: SFTPGO_SFTPD__BIND_ADDRESS
              value: "0.0.0.0"
            - name: SFTPGO_HTTPD__BIND_PORT
              value: "8080"
            - name: SFTPGO_HTTPD__BIND_ADDRESS
              value: "0.0.0.0" 
            - name: SFTPGO_LOG_VERBOSE 
              value: "true"
            - name: SFTPGO_SFTPD__HOST_KEYS
              value: '/etc/sftpgo/id_rsa,/etc/sftpgo/id_ed25519'
            - name: SFTPGO_LOADDATA_FROM 
              value: '/etc/sftpgo/users.json'
```
