### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by mcvoigt** [drakkan/sftpgo#304]
Hi,

When I try to access the telemetry page, I get a 404 error "page not found"
What can I be doing wrong and what can I do to correct it?

Thankful,
Michael Voigt

**Comment by drakkan** [comment]
Hi,

the telemetry server listen on port 10000 by default, please try:

```
http://localhost:10000/metrics
```

here is the default config you have in `sftpgo.json`

```
"telemetry": {
    "bind_port": 10000,
    "bind_address": "127.0.0.1",
    "enable_profiler": false,
    "auth_user_file": "",
    "certificate_file": "",
    "certificate_key_file": ""
  },
```

**Comment by mcvoigt** [comment]
Hi,
I found the way, and it works.
How should I use this data with Prometheus using the graphical interface? Could you provide a tutorial on how to configure and install Prometheus to have this graphical visualization?

Regards,
Mic

**Comment by drakkan** [comment]
Hi,

I have no time to write a full tutorial, sorry.

You can simply download and install prometheus as explained here:

https://prometheus.io/docs/prometheus/latest/getting_started/

modify `prometheus.yml` adding SFTPGo, for example:

```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:10000']
```

this assume that SFTPGo expose the metrics endpoind on `localhost:10000` (default configuration) and prometheus runs on the same host as SFTPGo.

Then open `http://localhost:9090/graph` and write `sftpgo` the autocomplete should show all the sftpgo metrics, select one and view the data as table and/or graph. You should see something like this

![Schermata del 2021-02-08 14-55-14](https://user-images.githubusercontent.com/553263/107229129-b6e52b00-6a1d-11eb-92bd-31d7f5b784b9.png)
