### ISSUE TITLE
httpd: SSL Medium Strength Cipher Suites Supported (SWEET32)

### ISSUE THREAD

**Issue by serveradmin99** [drakkan/sftpgo#316]
I have sftpgo all configured to use Let's Encrypt certificates.  I just did a Nessus scan and it tells me that the httpd is allowing medium strength ciphers:

  Medium Strength Ciphers (> 64-bit and < 112-bit key, or 3DES)

    Name                          Code             KEX           Auth     Encryption             MAC
    ----------------------        ----------       ---           ----     ---------------------  ---
    ECDHE-RSA-DES-CBC3-SHA        0xC0, 0x12       ECDH          RSA      3DES-CBC(168)          SHA1
    DES-CBC3-SHA                  0x00, 0x0A       RSA           RSA      3DES-CBC(168)          SHA1

I notice that there is no ciphers option under httpd in sftpgo.json.  Is there any way to specify the allowed ciphers for httpd?

Thanks

**Comment by drakkan** [comment]
Hi,

currently we only require TLS1.2 as a minimum version, I will make the ciphers configurable similar to how we do for SFTP, thanks for noticing

**Comment by drakkan** [comment]
This should be fixed now.

You can test this change using the `edge` variant if you are on docker or you can download distro packages [here](https://github.com/drakkan/sftpgo/actions/runs/579192497)

 please let me know if you have any issue.

If you have time, I really appreciate a PR with an [how-to style guide](https://github.com/drakkan/sftpgo/tree/main/docs/howto) that explains how to configure Let's Encrypt certificates and reloading them without service interruption. This would be useful for other users,  thank you

**Comment by serveradmin99** [comment]
> If you have time, I really appreciate a PR with an [how-to style guide](https://github.com/drakkan/sftpgo/tree/main/docs/howto) that explains how to configure Let's Encrypt certificates and reloading them without service interruption. This would be useful for other users, thank you

I'm not sure my implementation would suit other users to be honest.  I use ACME on a pfSense firewall with a script that copies the updated certs to the correct server:/path and runs `docker restart $(docker ps -qaf name=sftpgo)` on the docker host.

I use docker-compose to orchestrate the server.  I have an sftpgo folder containing the docker-compose.yml and sftpgodata and sfptgohome volumes.  The cert and key are copied to cert.pem and key.pem in the sftpgo folder.  Please note that the cert.pem includes the CA certificate as well as the host certificate.

docker-compose.yml:
```
version: '3.3'
services:
    sftpgo:
        container_name: sftpgo
        image: drakkan/sftpgo:latest
        ports:
            - '8443:8443'
            - '2022:2022'
        restart: always
        volumes:
            - type: bind
              source: ./sftpgodata
              target: /srv/sftpgo
            - type: bind
              source: ./sftpgohome
              target: /var/lib/sftpgo
            - type: bind
              source: ./sftpgo.json
              target: /etc/sftpgo/sftpgo.json
            - type: bind
              source: ./cert.pem
              target: /etc/sftpgo/cert.pem
            - type: bind
              source: ./key.pem
              target: /etc/sftpgo/key.pem
```
Relevant portion of sftpgo.json:
```
  "httpd": {
    "bindings": [
      {
        "port": 8443,
        "address": "",
        "enable_web_admin": true,
        "enable_https": true,
        "client_auth_type": 0
      }
    ],
    "templates_path": "templates",
    "static_files_path": "static",
    "backups_path": "/srv/sftpgo/backups",
    "certificate_file": "/etc/sftpgo/cert.pem",
    "certificate_key_file": "/etc/sftpgo/key.pem",
    "ca_certificates": [],
    "ca_revocation_lists": [],
    "ciphers": ["aes128-gcm@openssh.com","aes128-ctr", "aes192-ctr", "aes256-ctr"]
  },

```
There is an issue with using sftpgohome as a mounted volume in Docker.  If you run `docker-compose up -d`, the container will start and then die because there is no sftpgo.db found in /var/lib/sftpgo.  Ideally there should be a check for the database and a blank sftpgo.db should be created if not found.  I got around this by mounting sftpgohome elsewhere and copying sftpgo.db from inside the container.  Not ideal.
