### ISSUE TITLE
Empty OpenAPI enum values don't seem standard

### ISSUE THREAD

**Issue by ramnes** [drakkan/sftpgo#358]
Following #356, here is another thing that breaks the OpenAPI client generator I'm using:

```yaml
        access_tier:
          type: string
          enum:
            - ""
            - "Archive"
            - "Hot"
            - "Cool"
```

I've opened a PR for the generator (https://github.com/triaxtec/openapi-python-client/pull/358), but since it doesn't seem like a very standard OpenAPI practice, maybe it's something that you'd want to remove as well.
