### ISSUE TITLE
Strange Issue: New user home dir works however will not show up via ls

### ISSUE THREAD

**Issue by ravensorb** [drakkan/sftpgo#418]
Ok, so I am having a rather odd issue.  I created a new user via the web interface, allowed the "home dir" to automatically populate, logged in via WinScp and uploaded a few files -- everything worked great.  Then I went to the host OS and look at the data directory and the new home folder was not showing.  Even stranger -- I can still CD into it!  To make matters more interesting, if I try to remove the folder I get a message that it doesn't exist?

List of paths
![image](https://user-images.githubusercontent.com/2222472/118007607-469abe00-b31a-11eb-85c2-19eebf0840ea.png)

CD into the "missing" path
![image](https://user-images.githubusercontent.com/2222472/118007660-54e8da00-b31a-11eb-832c-3dca3b3cacb8.png)

Trying to remove the path
![image](https://user-images.githubusercontent.com/2222472/118007676-59ad8e00-b31a-11eb-8b9a-c428530531a1.png)

Note: If i create the path manually BEFORE adding it in the web interface, it works as I would expect.

**Comment by drakkan** [comment]
Well, this is strange. I have no idea. It seems you are testing in docker maybe is something related to bind mounts. Can you please share the steps to reproduce the issue? For example the used docker command, you local folder structure (if you mount a volume), the account type (local, cloud based) etc... 

If you create the path youself or if SFTPGo creates it for you should not make any difference

**Comment by ravensorb** [comment]
Here is my compose file - the mount points are just to other disks using ext4 filesystems

```
version: "3.7"

services:

  sftpgo:
    # https://hub.docker.com/r/drakkan/sftpgo
    container_name: sftpgo
    image: drakkan/sftpgo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user-data:/srv/sftpgo/data
      - /mnt/docker-appdata/server/sftpgo/config:/var/lib/sftpgo
      - /mnt/docker-appdata/server/sftpgo/backups:/srv/sftpgo/backups
    networks:
      - data
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    restart: always

networks:
  data:
    external: true
````

**Comment by drakkan** [comment]
Hi,

I just tested using this compose file

```
version: "3.7"

services:

  sftpgo:
    # https://hub.docker.com/r/drakkan/sftpgo
    container_name: sftpgo
    image: drakkan/sftpgo
    ports:
      - "8080:8080"
      - "2022:2022"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/sftpgo/data:/srv/sftpgo/data
      - /root/sftpgo/config:/var/lib/sftpgo
      - /root/sftpgo/backups:/srv/sftpgo/backups
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    restart: always

networks:
  data:
    external: true
```

I created the required directories with the correct owner and permissions:

```
pwd
/root/sftpgo
ls -la
totale 8
drwxr-xr-x   5 root root   73 13 mag 09.07 .
dr-xr-x---. 11 root root 4096 13 mag 09.03 ..
drwxr-xr-x   2 1000 1000    6 13 mag 09.03 backups
drwxr-xr-x   2 1000 1000  131 13 mag 09.09 config
drwxr-xr-x   3 1000 1000   20 13 mag 09.09 data
```

then I added a user from the web admin, I logged via SFTP using that user and I uploaded a file, the home dir was auto-created and I can read the created file just fine, so I'm unable to replicate the reported issue
