### ISSUE TITLE
Permissions on shared virtual folder - all operations (except list) report error 4

### ISSUE THREAD

**Issue by ravensorb** [drakkan/sftpgo#440]
I am curious if I am doing something wrong or if I hit a bug?  When users attempt to upload a file to the shared folder, they all get an error 4 message.  Note: they are able to see files in the folder, just cannot upload, delete, or rename

I have defined a virtual folder that is OUTSIDE of the sftp data folder structure
* Name: shared
* Path: /mnt/shared

Then I have updated two user profiles
* Virtual Folders: /shared::shared::0::0
* Sub dirs permissions: /shared::*

Does that look correct?  Or did I miss something?

Note: /mnt/shared has permissions set to 777 so it should not be a fs issue....

**Comment by drakkan** [comment]
Hi,

can you please post the SFTPGo logs? error 4 is not familar to me, thank you

**Comment by ravensorb** [comment]
Sorry should have added that :)

```
 {"level":"warn","time":"2021-05-27T13:52:19.851","sender":"SFTP","connection_id":"SFTP_c13ad55fd0d6292509586b277b65f4afa36f242ba1395fa6ff5dac61c95dd4d8_1","message":"failed to rename \"/srv/sftpgo/data/user1/test.txt\" -> \"/mnt/shared/test.txt\": rename /srv/sftpgo/data/user1/test.txt /mnt/shared/test.txt: invalid cross-device link"}
```

**Comment by drakkan** [comment]
cross folder rename is not supported

**Comment by ravensorb** [comment]
so how can files be moved between folders?

**Comment by drakkan** [comment]
I answered too quickly, I'm quite busy now sorry, cross folder rename is supported if both the source and target folder use the local filesystem. It is not supported if the source is on a cloud backend and the destination is a local path or viceversa, you likely have another issue

**Comment by ravensorb** [comment]
No worries -- was really impressed with how quickly you did respond :)

So both of these are local file systems -- I am running inside docker on a Ubuntu server and I am using standard bind mount points inside the container with full rw permissions.

**Comment by drakkan** [comment]
Please try a manual rename:

```
mv /srv/sftpgo/data/user1/test.txt /mnt/shared/test.txt
```

the error `invalid cross-device link` is not within SFTPGo source code

**Comment by ravensorb** [comment]
Just connected into the container and did a move (both directions) -- and both completed without issue

**Comment by drakkan** [comment]
It is likely a Go issue then, are you able to try the same from a small Go program? It seems the issue described here

https://gist.github.com/var23rav/23ae5d0d4d830aff886c3c970b8f6c6b

**Comment by drakkan** [comment]
This is strange, so `/mnt/shared` is the same local disk as `/srv/sftpgo/data` and you have issues only in `/mnt/shared`? Have you tryed to run the same system commands manually as the `sftpgo` user? Are you using a recent sftpgo version? Can you please try one on the edge variant to understand if this is a Go issue fixed in the latest version? 

Also please share the exact command used to start your docker image and your filesystem layout, I'll try to do a test myself later.

Thank you

**Comment by ravensorb** [comment]
Yep, the only different is where they are mapped to inside the container.  And yes, when I connect into the container I am using the sftpgo user (not root).

As for version, does this look correct: SFTPGo 2.0.4-f117d6d5-2021-04-10T06:49:15Z

Here is my docker-compose file:
```
version: "3.7"

services:

  sftpgo:
    # https://hub.docker.com/r/drakkan/sftpgo
    container_name: sftpgo
    image: drakkan/sftpgo
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data/shared:/shared
      - /mnt/data/user:/srv/sftpgo/data
      - /mnt/docker-appdata/server/sftpgo/config:/var/lib/sftpgo
    networks:
      - data
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    restart: always
```

**Comment by drakkan** [comment]
I can replicate the `invalid cross-device link` while renaming between docker bind mounts, the other things work for me.

In Go `os.Rename` calls the rename system call, and the rename system call can not rename files across devices (bind mounts are cross device in this context). As workaround you could use a single bind mount

**Comment by ravensorb** [comment]
Wouldn't that require me to move the shared folder into one of the users folders?  Then how do I get it to work for the other users?

**Comment by drakkan** [comment]
You can use `/srv/sftpgo` as bind mount. Users will have home dirs in `/srv/sftpgo/data/<username>` and you can set the folders path something like this `/srv/sftpgo/folders/<foldername>`. This works for me, including `rename`. 

However you seem to have also other issues with your bind mounts that I cannot replicate locally

**Comment by ravensorb** [comment]
Just to confirm you are thinking of a volume like this:

```
- /mnt/sftp-data:/srf/sftpgo
````

and then sftp would automatically create a subfolder called "data" that would handle user folders?

**Comment by drakkan** [comment]
Yes, I don't remember if we auto create folders in v2.0.x versions, but it works if you use the development version (`edge` tag)

**Comment by drakkan** [comment]
cross filesystem rename will now be internally converted to a copy, you can test this change using the `edge` or `edge-alpine` tag available in few minutes. I'm unable to replicate the other issue you reported

**Comment by ravensorb** [comment]
Ok, I'll give it a test this weekend and if I can figure out steps to replicate the other issues I'll open a new issue.  Thanks!

**Comment by drakkan** [comment]
I just did another test using this compose file:

```
version: "3.9"

services:
  sftpgo:
    container_name: sftpgo
    image: drakkan/sftpgo:edge-slim
    ports:
      - "8080:8080"
      - "2022:2022"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/sftpgo/data:/srv/sftpgo/data
      - /mnt/sftpgo/shared:/shared
    #environment:
    #  - SFTPGO_SFTPD__MAX_AUTH_TRIES=12
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    restart: always
```

please note the image name, you need an `edge` variant for cross device support.

When I try a cross rename I have now these logs:

```
{"level":"warn","time":"2021-05-27T23:02:43.270","sender":"osfs","connection_id":"3b9eca8ed93b2b4b49e1da90414bb761b4bcd6b84e9d740d76840f44896971b4","message":"cross device error detected while renaming \"/srv/sftpgo/data/nicola/ros.txt\" -> \"/shared/folder1/ros.txt\". Trying a copy and remove, this could take a long time"}
{"level":"info","time":"2021-05-27T23:02:43.270","sender":"Rename","username":"nicola","file_path":"/srv/sftpgo/data/nicola/ros.txt","target_path":"/shared/folder1/ros.txt","filemode":"","uid":-1,"gid":-1,"access_time":"","modification_time":"","size":-1,"ssh_command":"","connection_id":"SFTP_3b9eca8ed93b2b4b49e1da90414bb761b4bcd6b84e9d740d76840f44896971b4_1","protocol":"SFTP"}
```

I tested using WinSCP too and all works fine for me: upload/download/rename, delete
