### ISSUE TITLE
S3 directory mime type wrong?

### ISSUE THREAD

**Issue by FunnyGamer** [drakkan/sftpgo#451]
MinIO Browser and s3fs-fuse handles files with contentType "inode/directory" as files. This leads to no name files in MinIO Browser (Web UI) and buckets mounted with s3fs-fuse only shows 0 Byte files instead of directories. Changing dirMimeType constant to "application/x-directory" fixes this behaviour. Is it possible to set the dirMimeType to "application/x-directory" as default? Or if other Storage Types needs this media type then would it be possible to make the dirMimeType changeable via configuration?

**Comment by drakkan** [comment]
Hi,

it is strange, it seems to work for me, here is a screen from MinIO browser

![minio_browser](https://user-images.githubusercontent.com/553263/121062061-ebe36d80-c7c4-11eb-8a24-60cf2af1d90a.png)

I tested s3fs, this way:

```
s3fs test /tmp/s3  -o url="http://127.0.0.1:9000" -o passwd_file=creds -o use_path_request_style
```

and it seems to work too. Here are the versions I'm using

```
pacman -Q | grep minio
minio 2021.03.17-1
```

```
pacman -Q | grep s3fs
s3fs-fuse 1.88-1
```

I created the folders via SFTP using the `sftp` CLI.

Please give more details, I will be glad to fix if I'm able to replicate the issue, thank you

**Comment by FunnyGamer** [comment]
Thanks for the fast response! 

Here are some details:

I'm working on Linux Fedora 31 (Workstation Edition):
```
$ uname -a
Linux test-machine 5.8.12-100.fc31.x86_64 #1 SMP Mon Sep 28 13:03:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I started sftpgo with docker:
```
sudo docker run --rm -d --name sftpgo \
    --user 150080:520 \
    --add-host=host.docker.internal:host-gateway \
    -p 8090:8090 \
    -p 50000-50100:50000-50100 \
    -p 2022:2022 \
    -p 21:2021 \
    --mount type=bind,source="${PWD}/sftpgo_etc",target=/etc/sftpgo \
    --mount type=bind,source="${PWD}/data",target=/srv/sftpgo \
    --mount type=bind,source="${PWD}/config",target=/var/lib/sftpgo \
    -e SFTPGO_HTTPD__BINDINGS__0__PORT=8090 \
    -d "drakkan/sftpgo:v2.0.4"
```

and also tested it with a build:
```
$ go build
$ ./sftpgo serve
```

s3fs-fuse version:
```
$ s3fs --version
Amazon Simple Storage Service File System V1.87 (commit:unknown) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```
$ yum info s3fs-fuse
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:12 am Di 08 Jun 2021 11:13:58 CEST.
Installierte Pakete
Name         : s3fs-fuse
Version      : 1.87
Release      : 1.fc31
Architecture : x86_64
Size         : 758 k
Quelle       : s3fs-fuse-1.87-1.fc31.src.rpm
Repository   : @System
Aus Paketque : updates
Summary      : FUSE-based file system backed by Amazon S3
URL          : https://github.com/s3fs-fuse/s3fs-fuse
Lizenz       : GPLv2+
Description  : s3fs is a FUSE file system that allows you to mount an Amazon S3 bucket as a
             : local file system. It stores files natively and transparently in S3 (i.e.,
             : you can use other programs to access the same files). Maximum file size=64GB
             : (limited by s3fs, not Amazon).
             : 
             : s3fs is stable and is being used in number of production environments, e.g.,
             : rsync backup to s3.
```

MinIO configuration (docker-compose.yaml):
```
version: '3.7'

services:
  minio1:
    image: minio/minio:latest
    volumes:
      - ./data1-1:/data1
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server http://minio{1...4}/data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:latest
    volumes:
      - ./data2-1:/data1
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server http://minio{1...4}/data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:latest
    volumes:
      - ./data3-1:/data1
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server http://minio{1...4}/data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:latest
    volumes:
      - ./data4-1:/data1
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server http://minio{1...4}/data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
```

MinIO version:
```
$ docker image inspect minio/minio:latest | grep version
                "version": "RELEASE.2021-02-24T18-44-45Z"

```

I created the folders using FileZilla version 3.41.2:
![filezilla_version](https://user-images.githubusercontent.com/37621990/121162750-7c19c500-c84e-11eb-865d-6e414a875d1f.png)



FileZilla creation of "sftpgoTestDir":
![dir_creation](https://user-images.githubusercontent.com/37621990/121172318-d9feda80-c857-11eb-8858-86a495cb9652.png)




MinIO Browser:
![minio_view](https://user-images.githubusercontent.com/37621990/121165834-d87de400-c850-11eb-8786-902ca0221ccd.png)

![minio_view_into_dir](https://user-images.githubusercontent.com/37621990/121174828-a40f2580-c85a-11eb-82bf-8660ba9975c8.png)


s3fs-fuse mount:
```
$ s3fs test ./test-mount -o passwd_file=${HOME}/.passwd-s3fs -o url=http://127.0.0.1:9000/ -o use_path_request_style
$ ls -la test-mount/
insgesamt 5
drwx------ 1 test-user test-group    0  1. Jan 1970  .
drwxr-xr-x 3 test-user test-group 4096  8. Jun 12:00 ..
-rwxr-x--- 1 test-user test-group    0  8. Jun 11:56 sftpgoTestDir
```


Now, when i change `dirMimeType` of `vfs/vfs.go` to `"application/x-directory"` it works fine:

![create_dir2](https://user-images.githubusercontent.com/37621990/121173233-d9b30f00-c858-11eb-9831-0f3e4306ab60.png)

At first it doesn't work with still mounted folder:
```
ls -la test-mount/
insgesamt 6
drwx------ 1 test-user test-group    0  1. Jan 1970  .
drwxr-xr-x 3 test-user test-group 4096  8. Jun 12:00 ..
-rwxr-x--- 1 test-user test-group    0  8. Jun 11:56 sftpgoTestDir
-rwxr-x--- 1 test-user test-group    0  8. Jun 12:56 sftpgoTestDirWorking
```

But after remount it's working:
```
$ fusermount -u test-mount
$ s3fs test ./test-mount -o passwd_file=${HOME}/.passwd-s3fs -o url=http://127.0.0.1:9000/ -o use_path_request_style
$ ls -la test-mount/
insgesamt 6
drwx------ 1 test-user test-group    0  1. Jan 1970  .
drwxr-xr-x 3 test-user test-group 4096  8. Jun 12:00 ..
-rwxr-x--- 1 test-user test-group    0  8. Jun 12:54 sftpgoTestDir
drwxr-x--- 1 test-user test-group    0  8. Jun 12:57 sftpgoTestDirWorking
```

And now I see MinIO also displays the no name file of folder for the fixed version, but this is no problem for me:
![minio_view_inside_dir2](https://user-images.githubusercontent.com/37621990/121175305-31527a00-c85b-11eb-8cf0-05d90f22c3c5.png)
