### ISSUE TITLE
Unable to create_default_admin with different credentials

### ISSUE THREAD

**Issue by petrmvala** [drakkan/sftpgo#566]
Hi!

I am deploying the sftpgo in k8s and trying to setup default admin with some different credentials. That is, however, not working. Here is minimal working example of `deployment.yml` and `service.yml`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo-deployment
  labels:
    app: sftpgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      containers:
        - name: sftpgo
          image: drakkan/sftpgo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
              value: 'true'
            - name: SFTPGO_DEFAULT_ADMIN_USERNAME
              value: notadmin
            - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
              value: hahahaha
```

 ```
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-service
spec:
  selector:
    app: sftpgo
  ports:
    - name: admin-ui
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: sftp
      protocol: TCP
      port: 22
      targetPort: 2022
  type: LoadBalancer
```

With this setup, I would expect to login as admin with user `notadmin` and password `hahahaha`. That doesn't work. Instead, I can login using `admin`:`password`. Environment variables are present as they should:

```
➜  sftpgo git:(main) ✗ kubectl exec -it sftpgo-deployment-######### -- /bin/bash
sftpgo@sftpgo-deployment-#########:~$ env | grep ADMIN
SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
SFTPGO_DEFAULT_ADMIN_PASSWORD=hahahaha
SFTPGO_SERVICE_SERVICE_PORT_ADMIN_UI=80
SFTPGO_DEFAULT_ADMIN_USERNAME=notadmin
```
