### ISSUE TITLE
Unable to upload/download on S3

### ISSUE THREAD

**Issue by samyak-jain** [drakkan/sftpgo#592]
Hey,
I've been trying to use sftpgo with s3 backend. I have used the getting started guide and configured an S3 backend to a user I created called sftp. I only specificed the bucket name and region (I am not using access key and secret because I'm using an ECS task role). When I cannect to the server using sftp, I am able to list all files in the bucket but I cannot upload or download any of them. The reason I don't think this is a permission issue on my end is because as soon as I mount this same folder as a virtual folder, everything works. I am able to upload and download to the bucket. 

Here's my docker-compose config that I'm using:
```
services:
  sftp:
    image: drakkan/sftpgo:edge
    container_name: some-sftpgo
    stop_grace_period: 84m
    restart: always
    mem_limit: 471859200b
    ports:
      - "2022:2022"
    environment:
      - "SFTPGO_LOG_VERBOSE=true"
      - "SFTPGO_DATA_PROVIDER__DRIVER=sqlite"
      - "SFTPGO_DATA_PROVIDER__NAME=/var/lib/sftpgo/database.db"
      - "SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true"
      - "VIRTUAL_HOST=${sftp_domain}"
      - "LETSENCRYPT_HOST=${sftp_domain}"
    volumes:
      - sftp-files:/srv/sftpgo
      - sftp-data:/var/lib/sftpgo
    logging:
      driver: awslogs
      options:
        awslogs-group: sftp
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web

volumes:
  sftp-files:
  sftp-data:
```

I'm using this as an ECS task. I've tried the alpine, latest and edge docker images. 
Am I missing something obivous? Why is it working as a virtual folder but not when I'm using it as part of the user configuration? Let me know if I can provide any details to help.
