### ISSUE TITLE
Setting kex_algorithms in k8s manifest

### ISSUE THREAD

**Issue by stuartluscombe** [drakkan/sftpgo#857]
Hi,

We are using SFTPGo within an HA configuration on a AKS cluster and it's been working great. However we had an issue with the cloud provider a few days ago which meant the service had to auto-heal itself, part of that meant that the SFTPGo pods were re-created.

When this happened it pulled the latest image from the docker repository (2.2.3). It's working as expected except for one of our users  can't connect as they only support the following KEX algorithms:

diffie-hellman-group1-sha1
diffie-hellman-group14-sha1
diffie-hellman-group-exchange-sha

Looking back through the commits/changes to the application I can see that diffie-hellman-group14-sha1 used to be a default, but no longer is.

I tried to apply the environment variable for kex_algorithms with a value containing the defaults plus the above, but when applying that to the deployment the pods would not start as it was only accepting the first value in the string. Is this because the values need to be supplied as an array?

For the time being I've reverted the deployment back to v2.1.2 until I can work out a solution, but I wanted to know if there is a known, simple way of specifying the option without me having to move all custom configuration to a ConfigMap.

**Comment by drakkan** [comment]
> Hi,
> 
> We are using SFTPGo within an HA configuration on a AKS cluster and it's been working great. However we had an issue with the cloud provider a few days ago which meant the service had to auto-heal itself, part of that meant that the SFTPGo pods were re-created.
> 
> When this happened it pulled the latest image from the docker repository (2.2.3). It's working as expected except for one of our users can't connect as they only support the following KEX algorithms:
> 
> diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 diffie-hellman-group-exchange-sha
> 

sha1 based kex are disabled by default because sha1 is not considered secure anymore

> Looking back through the commits/changes to the application I can see that diffie-hellman-group14-sha1 used to be a default, but no longer is.
> 
> I tried to apply the environment variable for kex_algorithms with a value containing the defaults plus the above, but when applying that to the deployment the pods would not start as it was only accepting the first value in the string. Is this because the values need to be supplied as an array?
> 

this is because you specified one or more unsupported kex, the logs are your friends. The supported values are documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

> For the time being I've reverted the deployment back to v2.1.2 until I can work out a solution, but I wanted to know if there is a known, simple way of specifying the option without me having to move all custom configuration to a ConfigMap.

you can set all the configuration values as env vars or you can replace the default config file. Please note that v2.1.2 is not supported anymore and it also has some security issues, see the CVE for golang/crypto.

**Comment by stuartluscombe** [comment]
Thanks for the quick response.

> sha1 based kex are disabled by default because sha1 is not considered secure anymore

I have mentioned this to the user who has said they are going to be updating their system within the next month or so, hopefully resolving this issue I'm experiencing.

> this is because you specified one or more unsupported kex, the logs are your friends. The supported values are documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md)

I noticed that `diffie-hellman-group-exchange-sha` is not on the supported list so I have removed that from the list I'm trying to configure, but I am still experiencing an issue.

Here is an excerpt of my deployment manifest:

````yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo
  labels:
    app: sftpgo
  namespace: sftp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sftpgo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      containers:
        - env:
            - name: SFTPGO_COMMON__PROXY_PROTOCOL
              value: "1"
            - name: SFTPGO_COMMON__MAX_PER_HOST_CONNECTIONS
              value: "0"
            - name: SFTPGO_SFTPD__KEX_ALGORITHMS
              value: "curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group14-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1"
````

If I run this as-is then I receive an error stating:

`could not start SFTP server: unsupported key-exchange algorithm \" curve25519-sha256@libssh.org\"`

If I remove the KEX it is erroring on, then the error just moves to the next one, `ecdh-sha2-nistp256`.

> you can set one or more configuration values as env vars or you can replace the default config file. Please note that v2.1.2 is not supported anymore and it also has some security issues, see the CVE for golang/crypto.

This is why I'm wondering if I'll ultimately need to use a ConfigMap instead, as the env values within the manifest need to be strings and it feels like `kex_algorithms` needs to be an array.
