### ISSUE TITLE
Cannot manage Users nor Admins after upgrading to 2.3.1 (from 2.2.1)

### ISSUE THREAD

**Issue by StephaneBunel** [drakkan/sftpgo#911]
After upgrading I'm able to login on Web Admin with my credentials but I cannot anymore manage user nor admins (no buttons on interface). data_provider use sqlite driver. Web admin is accessed thru a proxy.

![Screenshot 2022-07-08 at 12-20-44 SFTPGo WebAdmin - Admins](https://user-images.githubusercontent.com/2349935/177974802-a0c4eeff-a3dc-4085-b9f0-1ae2db4e3f3b.png)

Config:
```yaml
common:
  upload_mode: 1
  actions:
    execute_on: [ "upload" ]
    hook: "{{ params.upload_hook }}"
  defender:
    enabled: true

sftpd:
  bindings:
    - address: {{ params.listen_address }}
      port: {{ params.listen_port }}

data_provider:
  driver: sqlite
  name: sqlite.db

httpd:
  bindings:
    - address: {{ params.listen_admin_address }}
      port: {{ params.listen_admin_port }}
      enable_web_admin: true
      enable_web_client: false
      enable_https: false

http:
  skip_tls_verify: true
```
