### ISSUE TITLE
Custom action not passing event arguments to hook command anymore

### ISSUE THREAD

**Issue by megamorf** [drakkan/sftpgo#976]
We've been using `drakkan/sftpgo:v2.1.2-slim` for a while and upgraded to `drakkan/sftpgo:v2.3-slim` today.
However, there seems to be a change in the custom hook behaviour in the new version:

Given the config:

```yaml
---
common:
  idle_timeout: 15
  upload_mode: 2
  actions:
    execute_on: ["upload"]
    execute_sync: []
    hook: '/tmp/importer.sh'
  setstat_mode: 0
  temp_path: ''
  # ...output omitted...
```

We had a script `/tmp/importer.sh` that processed the sftpgo arguments that were passed when the hook was triggered (simplified version here):

```sh
#!/usr/bin/env bash

set +x

echo "$@" >> /tmp/sftpgo-hook.log
echo "ACTION=$1 USER=$2 FILE=$3"
```

So assume the sftp user "john" uploads a file "images.zip".

## Expected

The `/tmp/importer.sh` script is called as follows:

```sh
/tmp/importer.sh upload john /srv/sftpgo/data/john/images.zip

# The output is:
ACTION=upload USER=john FILE=/srv/sftpgo/data/john/images.zip
```

## Actual

The script is called without arguments:

```
/tmp/importer.sh

# The output is:
ACTION= USER= FILE=
```

How can I replicate the old behaviour? I need to know which user uploaded which file in order to process it automatically.
